### ISSUE TITLE
Agent Owner Permissions

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopussy#106]
Add Permissions to user's agents.

Only the owner can change things in agent.php such as Agent parameters, machine name, and owner
Admins should be able to change owner in case of user error.

I almost wonder if it would be beneficial to have 2 separate agent active settings. One that gets unchecked if an error happens( and can be re-enabled by superuser + ), another that is only changeable by the agent owner.  both activity boxes must be checked to issue work.

**Comment by s3inlc** [comment]
all permissions for agents implemented until commit d2d6803
