### ISSUE TITLE
Adding new hashcat version - SQL bug

### ISSUE THREAD

**Issue by phillips321** [s3inlc/hashtopussy#112]
`[Fri Mar 03 10:48:05.166153 2017] [:error] [pid 1314] [client 192.168.0.46:60561] PHP Fatal error:  Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'level' at row 1 in /var/www/hashtopussy_v2/dba/AbstractModelFactory.class.php:121\nStack trace:\n#0 /var/www/hashtopussy_v2/dba/AbstractModelFactory.class.php(121): PDOStatement->execute(Array)\n#1 /var/www/hashtopussy_v2/dba/models/LogEntryFactory.class.php(87): DBA\\AbstractModelFactory->save(Object(DBA\\LogEntry))\n#2 /var/www/hashtopussy_v2/inc/Util.class.php(50): DBA\\LogEntryFactory->save(Object(DBA\\LogEntry))\n#3 /var/www/hashtopussy_v2/inc/handlers/HashcatHandler.class.php(50): Util::createLogEntry('User', '1', 'information', 'New hashcat rel...')\n#4 /var/www/hashtopussy_v2/inc/handlers/HashcatHandler.class.php(23): HashcatHandler::newHashcat()\n#5 /var/www/hashtopussy_v2/hashcat.php(26): HashcatHandler->handle('newhashcatp')\n#6 {main}\n  thrown in /var/www/hashtopussy_v2/dba/AbstractModelFactory.class.php on line 121, referer: http://192.168.0.44/hashcat.php?new=true`

**Comment by s3inlc** [comment]
Thanks for the report, to apply the change to an already installed hashtopussy you need to execute the following SQL statement:

`ALTER TABLE `LogEntry` CHANGE `level` `level` VARCHAR(21) NOT NULL`
