### ISSUE TITLE
Error: You need to specify a mask if you specify a custom-charset

### ISSUE THREAD

**Issue by bik3C0der** [s3inlc/hashtopussy#123]
I am having trouble running hasstopussy when using a custom charset (the DES one) and mask for DES.

Not 100% sure what I am doing wrong, I have set up the hashlists and everything correctly.

**Comment by blazer2x** [comment]
I believe this is a hashcat issue with v3.40 stable release.
Can you try and replace your hashcat files using the beta build from https://hashcat.net/beta/ or try compiling from the latest source.

See https://github.com/hashcat/hashcat/issues/1153 for more information

**Comment by winxp5421** [comment]
You can try to put your custom charset into an hcchar file ( which is what you should be doing anyway ) this helps keep the cli clear of escape characters or any other special characters that may interfere with Hashtopussy/ hashcat communication.

Usage is as follows
`hashcat64.xxx -a3 -m0 -1 custom.hcchar ?1?1?1?1?1`

**Comment by winxp5421** [comment]
Was this machine on the task from the beginning? 
Which benchmark method are you using, speed test or runtime?
Can you supply us with Benchmark values? both from the task with issues and from a separate task using the same hashlist as well as a benchmark from a completely different hashlist.


Just a word of caution be very careful manually editing the database.

**Comment by bik3C0der** [comment]
It joined the task about 1 minute behind the others.
Benchmark Type: Speed Test
How am I able to find the Benchmark values? They are only showing for that one machine on the task.

Yeah, I made sure to double check everything when editing the database.

**Comment by winxp5421** [comment]
Benchmark values are located in the task details page.  Assigned agents table under the benchmark column.

Also please provide us with the exact task command you are using to see if we can reproduce.
