### ISSUE TITLE
Question about keyspaces

### ISSUE THREAD

**Issue by jjensn** [s3inlc/hashtopussy#140]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
Hashtopussy: 0.3.1
Current Client version.
0.43.7

The exact task command you are trying to run.
-a0 #HL# -r best64.rule -r rockyou-30000.rule output.txt

Debug output from the client by running "hashtopussy.exe debug"
You are using the latest client version
System is Linux
Existing token found
{"action":"login","token":"hX4XCiHNSn"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"hX4XCiHNSn","force":0}
Hashcat version  found
Getting task
{"action":"task","token":"hX4XCiHNSn"}
{"action":"task","response":"SUCCESS","task":24,"attackcmd":"-a0 #HL# -r best64.rule -r rockyou-30000.rule output.txt -w 3","cmdpars":"-w3 --hash-type=2500","hashlist":1,"bench":30,"statustimer":5,"files":["best64.rule","rockyou-30000.rule","output.txt"],"benchType":"run","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"hX4XCiHNSn","hashlist":1}
{"action":"hashes","response":"SUCCESS","data":"**[Edited]**"}
Getting chunk...
{"action":"chunk","token":"hX4XCiHNSn","taskId":24}
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":677,"skip":41629,"length":2191}
/home/hashtopussy/hashcat/hashcat64.bin  -w3 --hash-type=2500 -a0 "/home/hashtopussy/hashlists/1"  -r "/home/hashtopussy/files/best64.rule" -r "/home/hashtopussy/files/rockyou-30000.rule" "/home/hashtopussy/files/output.txt" -w 3 --outfile-check-dir="/home/hashtopussy/hashlists/zaps1"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 41629 -l 2191

Describe your problem in as much detail as possible " It's broke " is not a description.

I ran hashcat with the above command, and it shows the following output:
@@@@@@@@@@@@@@@@@@@@@@@@@
Cache-hit dictionary stats /home/hashtopussy/files/output.txt: 898524551 bytes, 79728091 words, 184171890210000 keyspace
@@@@@@@@@@@@@@@@@@@@@@@@@

But in the UI it says my keysize is the same # as the wordlist.

Is that normal and expected?

**Comment by blazer2x** [comment]
Hi please see

https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#what_is_a_keyspace

Long story short, they number indicated as the keyspace on the UI may not necessary be indicative of the actual keysapce. Hashcat calculates this number based on several factors including the algorithm etc. If the number shown on the UI is matching that when the --keyspace is issued then it is correct.

**Comment by jjensn** [comment]
AFAIK if you have a wordlist with 79728091 words, and then you have rule lists which manipulates each word 1000 different ways, the keyspace can't possibly be the exact same count as the wordlist, right?
