### ISSUE TITLE
tasks not assigned

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopussy#142]
My first test running 100%
second test, client appear no new task assigned to agent
exist any manual steps for tasks?

**Comment by winxp5421** [comment]
It worked fine once, that means you have a configuration issue.
I dont have very much information to understand what is happening here but, make sure your client is marked as"trusted" and make sure your agent is marked "active"

https://github.com/s3inlc/hashtopussy/wiki/Frequent-Problems

**Comment by pccheck** [comment]
thanks for your time and attention

Where I find the commands to put before and after # HL #
Was not allocating because I just put # HL # rockyou.txt, it must be missing some parameter.
I did another test with
-a 3 #HL# ?d?d?d?d?d?d?d?d
it works

**Comment by winxp5421** [comment]
Please see here https://github.com/s3inlc/hashtopussy/wiki/Task-Creation-Guidelines
If you continue to have issues let us know.
`#HL# rockyou.txt` is a valid command are you sure your agent (client) is trusted!

**Comment by pccheck** [comment]
Great, very good. Congratulations for this tool, it was all I needed most.
thanks

**Comment by winxp5421** [comment]
Your very welcome. I will close this issue now. If you still have problems please re-open the issue.
