### ISSUE TITLE
LUKS 10 - 14600

### ISSUE THREAD

**Issue by ambasadorul** [s3inlc/hashtopussy#146]
Hello,

Could you please add support for uploading luksDump header files, that contains the information needed for attacking LUKS encrypted partitions.

Thank you and keep up with the good work.

**Comment by blazer2x** [comment]
Hi

This was an agent issue. Good pickup.
Agent Version 0.43.11 will have this resolved as json deserialization has been increased to 2GB limits.

This was been tested and a LUKS task was successfully cracked.

**Comment by s3inlc** [comment]
Basically, hashtopussy is able to handle all modes which hashcat supports, you can also add own modes if you use a forked hashcat.

LUKS headers are binary files, therefore they also should be uploaded just as binary hash and with the correct algorithm selected.

**Comment by s3inlc** [comment]
I'll close this issue now, as there is no issue with LUKS files anymore and the question was answered.
