### ISSUE TITLE
Change CPU only.

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopussy#148]
Currently, CPU only is selected at the Task level forcing users to create separate cpu only tasks and is not changeable once set.
This not only makes existing pre-configured tasks originally meant for gpu's not able to be issued to cpu only agents. you would have to create a separate preconfigured task each time you want to issue work to cpu only agents.

My suggestion is to move the cpu only "flag" to the hashlist level. So the hashlist can be a CPU only List instead of specific tasks governing CPU over GPU.

**Comment by s3inlc** [comment]
I agree in some points with your arguments.

But you can definitely use a pre-conf task and then set it either to cpu only or not, no matter as which type it was set when the pre-conf task was created.

I can not exactly say at the moment how complicated it will be if I move the cpu only config from the task to the hashlist, but it makes more sense, you're right.

**Comment by winxp5421** [comment]
For now please make CPU only and Small task changeable after task creation.
