### ISSUE TITLE
Creating task using pre-configured task does not send newTask notification.

### ISSUE THREAD

**Issue by soxrok2212** [s3inlc/hashtopussy#154]
Server version: 0.3.0
Client version: 0.43.11

Hey all, not looking for an immediate fix as I'm sure there are other priorities, but when creating a task from a pre-configured task, I don't receive a notification (web hooking through Discord). However, creating a task manually sends the notification.

That's all :)

**Comment by s3inlc** [comment]
I just tested. When I "copy" a task from the pre-config tasks list and then create it, I receive notifications.

Is it possible that you are talking about when you create a task from the Hashlists view with the pre-conf tasks which are displayed below?

**Comment by soxrok2212** [comment]
>Is it possible that you are talking about when you create a task from the Hashlists view with the pre-conf tasks which are displayed below?

Exactly. When I go to the hashlists page and create a task from there (with the checkboxes), I don't get a notification.

**Comment by s3inlc** [comment]
Ok that's right, there you don't get one. Your formulation was just not clear enough that it was clear you meant these pre-tasks.

I'll fix this as soon as possible.

**Comment by soxrok2212** [comment]
Right, I should have specified that. Thank you!

**Comment by s3inlc** [comment]
Now also notifications should be issued when creating tasks from the hashlist details view.

Just keep in mind that if you select for example 20 pre-conf tasks to create for this hashlist, you will get 20 notifications.

**Comment by soxrok2212** [comment]
Just tested, it works! Thank you 👍
