### ISSUE TITLE
error nvidia

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopussy#155]
what is this error?
Client Version 0.43.12
Checking for client updates
You are using the latest client version
System is Windows
Existing token found
Logged in to server
Hashcat version v3.40-90-g418341b found
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
nvmlDeviceGetCurrPcieLinkWidth(): Not Supported
nvmlDeviceGetClockInfo(): Not Supported
nvmlDeviceGetClockInfo(): Not Supported
nvmlDeviceGetTemperatureThreshold(): Not Supported
nvmlDeviceGetTemperatureThreshold(): Not Supported
nvmlDeviceGetUtilizationRates(): Not Supported
clWaitForEvents(): CL_OUT_OF_RESOURCES

nvidia driver stop
is ocurred after update this client to hashcat version 3.5 beta
before running ok

**Comment by winxp5421** [comment]
Hashcat errors

**Comment by blazer2x** [comment]
If you aren't able to run hashcat -b without errors, it means hashtopussy won't work.
Probably best to test that.
