### ISSUE TITLE
Hashtopussy over internet?

### ISSUE THREAD

**Issue by atao** [s3inlc/hashtopussy#156]
Hello,
Is it possible to use Hashtopussy server over internet? Or it can be use only over lan?
Thanks and good job!

**Comment by winxp5421** [comment]
It can be used over both. for obvious reasons use SSL!

**Comment by atao** [comment]
SSL is an obligation over internet?
Sur, i use it with SSL, but for a test, i want test it with free hosting with no ssl...

**Comment by winxp5421** [comment]
You can without but, don't put anything sensitive on it
