### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopussy#158]
Hi,

I have 3 computers same configuration, same drivers and versions hashcat
but benchmark is diferent
whats this?
see details task and agents
[taskdetails.pdf](https://github.com/s3inlc/hashtopussy/files/907113/taskdetails.pdf)
[agents.pdf](https://github.com/s3inlc/hashtopussy/files/907114/agents.pdf)

**Comment by winxp5421** [comment]
What Clients are you talking about? you cannot just assume we know everything about your setup. IORNPC 1, 2, and 3 all look the same to me.

**Comment by pccheck** [comment]
sorry,
agents: iornpc iornpc2 and iornpc3
same configuration, same drivers, same clients and hashcat
but benchmark is diferent

**Comment by winxp5421** [comment]
They are the same, they all have a benchmark of "0.00457351" i dont see a problem here.

**Comment by winxp5421** [comment]
I see what you are saying. The benchmarks are all the same but, the Chunk sizes are different.

**Comment by pccheck** [comment]
I forced these values, to see if it was with equal performance iorn pc 161kH / s
But iornpc2 and iornpc3 49000H / s

**Comment by s3inlc** [comment]
Can you please make a screenshot of the task with showing all chunks (by clicking on 'show latest 100)

**Comment by winxp5421** [comment]
"I forced these values, to see if it was with equal performance iorn pc 161kH / s
But iornpc2 and iornpc3 49000H / s"

OK, Manually changing things and not telling us you manually changed them. This is information we would like to know about. We cannot troubleshoot what is happening with HTP if you are changing values and then posting altered settings. We want to help and make HTP better, however, you need to give us the full story, not just bits and pieces.

**Comment by winxp5421** [comment]
This is now 5 days old and i can assume the data we are looking for is probably gone. If anyone notices that this is still an issue please reopen.
