### ISSUE TITLE
Some tasks cause an OutOfRangeException

### ISSUE THREAD

**Issue by soxrok2212** [s3inlc/hashtopussy#160]
Server Version: 0.3.0
Client Version: 0.43.12
Hashcat version: 3.5.0

Command: #HL# -a 3 ?d?d?d?d?d?d?d?d?d
Debug output:
```
Getting chunk...
STATUS  2       SPEED   234     1       EXEC_RUNTIME    67.281848       CURKU   10485760        PROGRESS        105381888       199229440       RECHASH 0       5       RECSALT 0       1       REJECTED        0
STATUS  5       SPEED   230     1       EXEC_RUNTIME    67.113657       CURKU   10485760        PROGRESS        105906176       199229440       RECHASH 5       5       RECSALT 1       1       REJECTED        0
Attack finished
Progress:  0.56% | Speed:234.00KH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:2
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at hashtopussy.taskClass.threadPeriodicUpdate(List`1& uploadPackets, Object& objPacketlock)
Error processing packet for upload
```
Was gone for a while, then I ran a 9 digit task on WPA/WPA2 and this happened. Not quite sure what other information I can provide. Server is completely vanilla and we didn't change anything that should cause this in the agent (IIRC it happens in vanilla agent too).

**Comment by s3inlc** [comment]
We suspect that this is a special case which happens only when multiple hccapx get cracked. Can you confirm that it only happens on WPA?

It would help us a lot if you could send us the corresponding hccapx (pm me on my email) and is possible also the plains so we can try to reproduce and fix the bug.

**Comment by soxrok2212** [comment]
I have ONLY been testing WPA on this server. The hccapx is on hashkiller forums, was using for testing purposes: https://forum.hashkiller.co.uk/topic-view.aspx?t=18501&m=128555
SSID: b760b0
The password is already recovered for reference, and yes, hashtopussy reports 5 hashes in the file.

**Comment by s3inlc** [comment]
Thanks, we'll investigate this.

**Comment by soxrok2212** [comment]
The first time I ran, it actually made it to the point where it recovered the password, then crashed instantly. The password was not put in the database either, I only got a notification that it had been cracked.

**Comment by soxrok2212** [comment]
It seems that an 8 digit bruteforce also caused this error. So far seems to only be with masks.

**Comment by blazer2x** [comment]
Bug fixed.
https://github.com/s3inlc/hashtopussy-agent/commit/a44a89b308fa2d34a6f126ad3dfd1dcd0d4852b0

**Comment by soxrok2212** [comment]
Thank you! I'll test it out in a bit.
