### ISSUE TITLE
Waiting for unfinished HTTP connections

### ISSUE THREAD

**Issue by rgw810** [s3inlc/hashtopussy#164]
I have a setup with about 20 computers and most, not all computers have had this issue. Some take longer than others though, the agents will finish their first chunk of activity and then drop the connection. I've had some agents run through 2 chunks and then drop the connection. They are the same deployed image using the same driver for AMD. They were on a domain and some were removed for troubleshooting with the same results.

I've used Hashcat 3.10 and 3.30 and the same thing has happened, domain, no domain, IPV4, or IPV6. Any thoughts?? OS is Windows 10 Enterprise
![capture](https://cloud.githubusercontent.com/assets/11729295/24955014/b42bc51c-1f4f-11e7-8df3-6a52a8f24f7a.PNG)

**Comment by blazer2x** [comment]
You are asking about a legacy version of hashtopussy. You may want to test out this version and see if the problem persists.

**Comment by rgw810** [comment]
Not able to install it, keep getting HTTP 500 Internal Error. The database is filled with the SQL commands. No errors in the any logs.......only thing I notice with the new one is no server.php in the download

**Comment by winxp5421** [comment]
What kind of virtual environment are you running the server in. I have had issues with proxmox.

**Comment by winxp5421** [comment]
Did you fully remove the old hashtopussy legacy install. There is no way to upgrade hashtopussy legacy. You need a full removal and install

**Comment by rgw810** [comment]
running XAMPP v5.6 for Apache and SQL, and yes removed the entire HTDOCS folder containing the old version. I input the DB info for a new install and the redirect after the DB is filled puts out the HTTP 500 Internal Error.

**Comment by s3inlc** [comment]
Ok, in src/inc/load.php set ```ini_set("display_errors", "1")``` and then try again and post what is printed as error message

**Comment by rgw810** [comment]
Fatal error : Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\install\index.php line 69

**Comment by s3inlc** [comment]
Ok, please raise this value, depending on the mysql-server it can take some time to install the initial sql into the db.

**Comment by rgw810** [comment]
Okay, I tried to make the change for the time and still got the error, not sure it was correct line,  where should the change be made to increase the time?

**Comment by winxp5421** [comment]
ini_set("display_errors", "1") should give you more information

**Comment by rgw810** [comment]
![capture](https://cloud.githubusercontent.com/assets/11729295/24957759/c552c5d8-1f5a-11e7-90a5-68f9ec95e6b7.PNG)
 Line 69 is whats reported as the error

**Comment by rgw810** [comment]
Downloaded client with voucher,  Unsupported 16-Bit Application message. 

Is Hashtopussy not compatible with 64-bit versions of Windows? Running Windows 10 Enterprise 2016

**Comment by winxp5421** [comment]
This runs fine on W10 non enterprise. I don't see why it would not run. Maybe a policy keeping windows from running a "unsigned" exe?

**Comment by winxp5421** [comment]
Also make sure you have .NET runtime installed ( maybe Enterprise does not have this installed by default)

**Comment by rgw810** [comment]
Checked that first, came with the OS. I tested on Windows 7 64bit and got the same error
![capture](https://cloud.githubusercontent.com/assets/11729295/24962625/6fefecd2-1f6a-11e7-947b-d685c29cd697.PNG)

I uploaded the executable if you wanted to take a look at it
[Hashtopus Agent ](http://www.fast-files.com/getfile.aspx?file=135835)

**Comment by winxp5421** [comment]
What is the size of the hashtopussy.exe file?
Can you pull the exe straight from the web server without downloading through the web UI `/src/static/hashtopussy.exe` and see if it runs?
I don't mess with crappy file downloading sites.

**Comment by rgw810** [comment]
It's 56KB, and that runs and asks for a server connect URL

**Comment by winxp5421** [comment]
Which URL are you supplying the client with?
Is there any more info if you run `hashtopussy.exe debug`?

**Comment by rgw810** [comment]
Got it, ran the provided download link and not the download button after adding voucher, once link was placed it worked.

**Comment by winxp5421** [comment]
This seems strange as the button and Link are the same thing. 
You must have somehow gotten a corrupt download. 
Let us know if you run into any other issues
