### ISSUE TITLE
.net version 4.0 not supported on client

### ISSUE THREAD

**Issue by gurreP** [s3inlc/hashtopussy#167]
Hashtopussy: 0.3.1
Client Windows 7 x64. .Net v 4.0

hashtopussy.exe try to load files from server,  use url like `http:\/\/xxx.xxx.xxx.xxx\/static\/[file] and crash with` error/

 .Net v 4.5 works normal.

**Comment by winxp5421** [comment]
Please follow the issue template we need more information than this in order to get a better idea of what is going wrong.

**Comment by gurreP** [comment]
client add backslash `\` to url and can not load files from server

**Comment by winxp5421** [comment]
Can you give us Client debug output please. so we can verify.

**Comment by winxp5421** [comment]
Closing this it's been open for the better part of a year with Incomplete information.
