### ISSUE TITLE
increment mod

### ISSUE THREAD

**Issue by atao** [s3inlc/hashtopussy#169]
Is it possible to add incremental mod?
Not found for me...

Server : 0.3.1
Client : 0.43.12
Hashcat : 3.5.0

**Comment by winxp5421** [comment]
Hashcat does not support -l -s while using -i or mask files so no we cannot directly add incremental to HTP in the sense you want. However, we are working on something to help in the creation of these tasks. https://github.com/s3inlc/hashtopussy/issues/122

**Comment by atao** [comment]
Okay, thanks!
