### ISSUE TITLE
BAD Preformance

### ISSUE THREAD

**Issue by pccheck** [s3inlc/hashtopussy#170]
Hello,
I reinstalled everything
Server and clients
And now I have a performance much lower than expected
See task and agent details
Try before speed benchmark and agents marked 0,00Hs
thank you
[agent3.pdf](https://github.com/s3inlc/hashtopussy/files/920981/agent3.pdf)
[agent2.pdf](https://github.com/s3inlc/hashtopussy/files/920978/agent2.pdf)
[agent1.pdf](https://github.com/s3inlc/hashtopussy/files/920979/agent1.pdf)
[task.pdf](https://github.com/s3inlc/hashtopussy/files/920980/task.pdf)

**Comment by s3inlc** [comment]
These benchmarks look really wrong. Normally these numbers should be below 1 on runtime benchmarks. Something went really wrong there.

**Comment by winxp5421** [comment]
What hashcat version are you running?

**Comment by pccheck** [comment]
3.5.0 stable

**Comment by pccheck** [comment]
I set manual values and get better benchmark

[task2.pdf](https://github.com/s3inlc/hashtopussy/files/921146/task2.pdf)

**Comment by kawuum** [comment]
I have exactly the same problem. The numbers are greater than 2 and performance is really bad. If I manually set the benchmark number to 1, the performance increases (about 2x faster, comparable to using hashcat without hashtopussy server).

**Comment by s3inlc** [comment]
Which numbers are greater than 2, the benchmark result? Were you using runtime benchmark?

**Comment by kawuum** [comment]
Right, I was talking about the benchmark numbers, which are >2.

I was indeed using runtime benchmark.

**Comment by s3inlc** [comment]
As these numbers are very high for a benchmark result, what kind of task are we talking about? Is this a very small task?

**Comment by kawuum** [comment]
No, it is a pretty large task which is estimated to run for weeks on a gpu cluster.

**Comment by s3inlc** [comment]
Then something must be pretty wrong on the benchmark result. Because the runtime benchmark number says, how much of the whole task the agent is able to complete in 100 seconds. So in case the benchmark result says 2, this would mean the agent would be able to complete the task 2 times in 100 seconds which cannot be as you say it's a large task.

Do you have some information on the task you are running?

**Comment by kawuum** [comment]
Strange. Something must really have been going wrong. I deleted the task, created it again and now everything seems to work fine (i.e. benchmark numbers are way below 1).

**Comment by s3inlc** [comment]
Ok great, if it happens again, please try to remember the actions which lead to it and report again.

**Comment by winxp5421** [comment]
House cleaning, Closing this its been open for a while and many improvements have been made since this was an issue.
