### ISSUE TITLE
First steps "tutorial" after installation

### ISSUE THREAD

**Issue by s3inlc** [s3inlc/hashtopussy#173]
It may help for new users to provide some sort of tutorial to introduce the different features and first steps on using hashtopussy.
This should be available after a successful installation to be activated or not.

**Comment by winxp5421** [comment]
A similar youtube video approach should be sufficient until this gets fully implemented. I will work on getting this published soon.

**Comment by s3inlc** [comment]
Ok, then we could maybe show the links of the youtube tutorials directly after installation, so if users don't know how to start using it, they could watch the videos.

**Comment by jepunband** [comment]
hi @s3inlc  can you direct me to the video tutorial on how to use the tool after the setup of the server, just like the video you made on the installation part.

thanks.
