### ISSUE TITLE
Error processing packet for upload

### ISSUE THREAD

**Issue by diamond2k** [s3inlc/hashtopussy#174]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
Hashtopussy: 0.3.0
Current Client version.
Client Version 0.43.2
The exact task command you are trying to run.
 -a 3 #HL# ?u?u?u?u?u?u?u?u

Debug output from the client by running "hashtopussy.exe debug"
____________________________________________________________________
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\R9 295x2\Desktop\hashtopussy>hashtopussy debug
Client Version 0.43.2
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.2"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"kCvt4w46LX"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"kCvt4w46LX","force":0}
Hashcat version v3.5.0 found
Getting task
{"action":"task","token":"kCvt4w46LX"}
{"action":"task","response":"SUCCESS","task":2,"attackcmd":"-a 3 #HL# ?u?u?u?u?u?u?u?u","cmdpars":" --hash-type=2500","hashlist":1,"bench":30,"statustimer":5,"files":[],"benchType":"speed","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"kCvt4w46LX","hashlist":1}
{"action":"hashes","response":"SUCCESS","data":""}
{"action":"chunk","token":"kCvt4w46LX","taskId":2}
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":202,"skip":713439232,"length":2050048}
C:\Users\R9 295x2\Desktop\hashtopussy\hashcat\hashcat64.exe   --hash-type=2500 -a 3 "C:\Users\R9 295x2\Desktop\hashtopussy\hashlists\1"  ?u?u?u?u?u?u?u?u --outfile-check-dir="C:\Users\R9 295x2\Desktop\hashtopussy\hashlists\zaps1"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 713439232 -l 2050048
STATUS  2       SPEED   184     1       179     1       EXEC_RUNTIME    6.985499        7.134966    CURKU       713439232       PROGRESS        18550411264     18602721280     RECHASH 0       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
{"action":"solve","token":"kCvt4w46LX","chunk":202,"keyspaceProgress":713439232,"progress":18550411264,"total":18602721280,"speed":363,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:1.86% | Speed:363KH/s | Cracks:0 | Accepted:0 | Zapped:0 | Queue:1
STATUS  2       SPEED   182     1       178     1       EXEC_RUNTIME    6.968707        7.134625    CURKU       713439232       PROGRESS        18552393728     18602721280     RECHASH 0       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
{"action":"solve","token":"kCvt4w46LX","chunk":202,"keyspaceProgress":713439232,"progress":18552393728,"total":18602721280,"speed":360,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:5.58% | Speed:360KH/s | Cracks:0 | Accepted:0 | Zapped:0 | Queue:1
STATUS  2       SPEED   182     1       178     1       EXEC_RUNTIME    6.965597        7.192341    CURKU       713439232       PROGRESS        18554128384     18602721280     RECHASH 0       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
{"action":"solve","token":"kCvt4w46LX","chunk":202,"keyspaceProgress":713439232,"progress":18554128384,"total":18602721280,"speed":360,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:8.83% | Speed:360KH/s | Cracks:0 | Accepted:0 | Zapped:0 | Queue:1
STATUS  2       SPEED   183     1       178     1       EXEC_RUNTIME    6.998549        7.121227    CURKU       713439232       PROGRESS        18555863040     18602721280     RECHASH 0       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
{"action":"solve","token":"kCvt4w46LX","chunk":202,"keyspaceProgress":713439232,"progress":18555863040,"total":18602721280,"speed":361,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:12.09% | Speed:361KH/s | Cracks:0 | Accepted:0 | Zapped:0 | Queue:1
STATUS  2       SPEED   183     1       178     1       EXEC_RUNTIME    6.955023        7.144079    CURKU       713439232       PROGRESS        18557845504     18602721280     RECHASH 0       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
{"action":"solve","token":"kCvt4w46LX","chunk":202,"keyspaceProgress":713439232,"progress":18557845504,"total":18602721280,"speed":361,"state":2,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:15.81% | Speed:361KH/s | Cracks:0 | Accepted:0 | Zapped:0 | Queue:1
STATUS  2       SPEED   182     1       178     1       EXEC_RUNTIME    6.950823        7.122120    CURKU       713439232       PROGRESS        18559580160     18602721280     RECHASH 3       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
STATUS  2       SPEED   182     1       178     1       EXEC_RUNTIME    7.019596        7.145878    CURKU       713439232       PROGRESS        18561314816     18602721280     RECHASH 3       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
STATUS  2       SPEED   183     1       178     1       EXEC_RUNTIME    6.977079        7.222823    CURKU       713687040       PROGRESS        18563049472     18602721280     RECHASH 3       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
STATUS  2       SPEED   182     1       178     1       EXEC_RUNTIME    6.999333        7.171891    CURKU       713687040       PROGRESS        18565031936     18602721280     RECHASH 3       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
STATUS  2       SPEED   182     1       178     1       EXEC_RUNTIME    7.066316        7.182326    CURKU       713687040       PROGRESS        18566766592     18602721280     RECHASH 3       4       RECSALT        0       1       TEMP    -1      -1      REJECTED        0
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Error processing packet for upload
^C
C:\Users\R9 295x2\Desktop\hashtopussy>
______________________________________________________________________________________
Describe your problem in as much detail as possible " It's broke " is not a description.
______________________________________________________________________________________
It started on both nodes after 201 chunk has been passed.

**Comment by winxp5421** [comment]
I am hoping this is just an outdated client issue the only negative number i see is the gpu temp. 

Please replace your existing hashtopussy.exe on your server ( /var/www/hashtopussy/static ) with https://github.com/s3inlc/hashtopussy/blob/master/src/static/hashtopussy.exe 

BE SURE to update the agent version number in the server webui.

Report back if this fixes the issue.

**Comment by diamond2k** [comment]
it SOLVED! Thanks a lot!

**Comment by winxp5421** [comment]
Awsome! if you have any other issues be sure to let us know here. As we will get notified faster :)

**Comment by diamond2k** [comment]
Awesome! A little more bug info:
i said: "It started on both nodes after 201 chunk has been passed."
Chunk 202: This piece had the key!!! After i have changed the updated client, 202 could pass and i have the key!
I hope one day i can give you some bier, 1 for hashtopus video, 1 for the hashtopussy and at least 1 more for this help.
This is great work guys, special thanks for s3inlc.
