### ISSUE TITLE
 upgrading to HTP 0.3.1

### ISSUE THREAD

**Issue by diamond2k** [s3inlc/hashtopussy#176]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
 0.3.0
Current Client version.
0.43.13
The exact task command you are trying to run.
Update from 0.3.0 to 0.3.1
Debug output from the client by running "hashtopussy.exe debug"

Describe your problem in as much detail as possible " It's broke " is not a description.
How to update server? I have downloaded  update_v0.3.0_v0.3.1.php to install/updates/ and chmod 775
it doesn't come up in browser. Can you give some instruction please?

**Comment by winxp5421** [comment]
I realize we have not written documentation on the upgrading process yet. It sounds like you just downloaded the update.php and nothing else? 

I hope you made backups as I'm not entirely sure what you have or have not done. Critical files that need to be backed up are /inc/Load.php and /inc/Encryption.class.php these files are critical.

When you say "it doesn't come up in the browser" do you get any errors at all or just a blank page?

You need to update your entire Hashtopussy root folder. With git or manually extracting the zip depending on which method you originally used to install HTP.

**Comment by diamond2k** [comment]
i have backed up the vm and moved to a different hypervisor, and its working fine both place.
doesnt come up means: 404 on the update_v0.3.0_v0.3.1.php. Hastopussy still works fine, i havent change anything.
Originaly i have installed hashtopussy based on your your server install video.

**Comment by s3inlc** [comment]
Generally, the update scripts are designed to be called via command line e.g.:

`php -f install/updates/update_v0.3.0_v0.3.1.php`

But theoretically it works in the browser too.

**Comment by winxp5421** [comment]
Please make sure you backup  `/inc/Load.php` and `/inc/Encryption.class.php` and `/files` before attempting to update. 

If `/home/<user>/hashtopussy` still exists please remove with `rm -r hashtopussy` then redownload hashtopussy with `git clone https://github.com/s3inlc/hashtopussy.git` ( you can also just use `git pull` without deleting that folder but removal and cloning ( i as the troubleshooting help can be certain you have a good copy)) 

Once you have an updated git repo you can replace your current working install with the new version.
`cp /home/<user>/hashtopussy/src/* /var/www/hashtopussy/`
Restore your load.php, Encryption.class.php, files dir.
`cp ./load.php /var/www/hashtopussy/inc/`
`cp ./Encryption.class.php /var/www/hashtopussy/inc/`

Load upgrade script
`php -f install/updates/update_v0.3.0_v0.3.1.php`

Your upgrade should be complete.

**Comment by winxp5421** [comment]
Upgrading wiki page has been added. I will close this for now @diamond2k If you run into issues feel free to re-open this issue.

**Comment by diamond2k** [comment]
developer@vs-hastopussy:/var/www/hashtopussy$ sudo php -f install/updates/update_v0.3.0_v0.3.1.php
Apply updates...
Update Zap table... OK
Check csharp binary... update version... OK
Update complete!

but still
Hashtopussy: 0.3.0 - About

**Comment by s3inlc** [comment]
Did you checkout the exakt tag v0.3.0 or did you just updated to the current master branch?

**Comment by diamond2k** [comment]
just bottom of the page and about: Hashtopussy version 0.3.0 running on 192.168.1.33.

**Comment by diamond2k** [comment]
i did backup and copied following winxp comment, and then i issued sudo php -f install/updates/update_v0.3.0_v0.3.1.php

**Comment by s3inlc** [comment]
Yeah I know where you mean. But at the exact v0.3.1 tag the version number was not updated. So in case you just cloned exactly the release tag it shows 0.3.0 even if it's 0.3.1. 
But I recommend to use the current master as it contains some bugfixes which exist in 0.3.1 release.
