### ISSUE TITLE
Maskprocessor support

### ISSUE THREAD

**Issue by soxrok2212** [s3inlc/hashtopussy#177]
Just a feature request, though I'm not sure how easy/feasible it would be in a distributed setup.

Maskprocessor allows for huge keyspace reductions when properly used, can turn some 1 week tasks to a few days. I understand that it would require the server to be generating the keysapce with rules on the fly, but would it be possible for hashtopussy to support this? Would be HUGE, particularly for WPA/WPA2 where large tasks (9/10 hex) can be brought down quite a bit.

Thanks!

**Comment by s3inlc** [comment]
We planned to have an import for Hashtopussy where you could import hcmask files as supertasks where you can issue them then for a hashlist.

See here: https://github.com/s3inlc/hashtopussy/issues/116

**Comment by winxp5421** [comment]
I think i am going to label this as a duplicate and close. If for some reason you feel this needs to be added to please post in issue #116
