### ISSUE TITLE
OSX client

### ISSUE THREAD

**Issue by diamond2k** [s3inlc/hashtopussy#182]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.3.1
Current Client version.
0.43.13
The exact task command you are trying to run.
Running OSX client
Debug output from the client by running "hashtopussy.exe debug"

sudo mono hashtopussy.exe debug
Client Version 0.43.13
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.13"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Mac
Existing token found
{"action":"login","token":"qeRXTe0XWF"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"qeRXTe0XWF","force":1}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2611k  100 2611k    0     0  34.7M      0 --:--:-- --:--:-- --:--:-- 34.9M
/Users/hiddenhelper/Desktop/Hashtopussy/7zr x -y -o"/Users/hiddenhelper/Desktop/Hashtopussy/hcClient" "/Users/hiddenhelper/Desktop/Hashtopussy/hcClient.7z"
Extracting archive /Users/hiddenhelper/Desktop/Hashtopussy/hcClient.7z...

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs x64)

Scanning the drive for archives:
1 file, 2674373 bytes (2612 KiB)                  

Extracting archive: /Users/hiddenhelper/Desktop/Hashtopussy/hcClient.7z
--
Path = /Users/hiddenhelper/Desktop/Hashtopussy/hcClient.7z
Type = 7z
Physical Size = 2674373
Headers Size = 5928
Method = LZMA2:26
Solid = +
Blocks = 1

Everything is Ok                         

Folders: 39
Files: 602
Size:       57525422
Compressed: 2674373
Applying execution permissions to 7zr binary
Could not locate hashcat binary
You can manually download and extract hashcat
Client will now terminate
chmod: /Users/hiddenhelper/Desktop/Hashtopussy/hashcat/hashcat: No such file or directory
Hiddens-Mac:Hashtopussy hiddenhelper$ sudo mono hashtopussy.exe
Password:
Client Version 0.43.13
Checking for client updates
You are using the latest client version
System is Mac
Existing token found
Logged in to server
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2611k  100 2611k    0     0  54.0M      0 --:--:-- --:--:-- --:--:-- 54.2M
/Users/hiddenhelper/Desktop/Hashtopussy/7zr x -y -o"/Users/hiddenhelper/Desktop/Hashtopussy/hcClient" "/Users/hiddenhelper/Desktop/Hashtopussy/hcClient.7z"
Extracting archive /Users/hiddenhelper/Desktop/Hashtopussy/hcClient.7z...
open: invalid option -- y
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-s <partial SDK name>][-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.
      -s                For -h, the SDK to use; if supplied, only SDKs whose names contain the argument value are searched.
                        Otherwise the highest versioned SDK in each platform is used.

Unhandled Exception:
System.IO.DirectoryNotFoundException: /Users/hiddenhelper/Desktop/Hashtopussy/hcClient/hashcat-3.5.0 does not exist
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000e4] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at hashtopussy.hashcatUpdateClass.updateHashcat () [0x001bc] in <7a7f1fcab7204586a6876fb631c6c5e2>:0 
  at hashtopussy.Program.Main (System.String[] args) [0x00167] in <7a7f1fcab7204586a6876fb631c6c5e2>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: /Users/hiddenhelper/Desktop/Hashtopussy/hcClient/hashcat-3.5.0 does not exist
  at System.IO.Directory.Move (System.String sourceDirName, System.String destDirName) [0x000e4] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at hashtopussy.hashcatUpdateClass.updateHashcat () [0x001bc] in <7a7f1fcab7204586a6876fb631c6c5e2>:0 
  at hashtopussy.Program.Main (System.String[] args) [0x00167] in <7a7f1fcab7204586a6876fb631c6c5e2>:0 
Hiddens-Mac:Hashtopussy hiddenhelper$

Describe your problem in as much detail as possible " It's broke " is not a description.
Could you give some instructions, how to use this 7zr.osx? 2nd time I tried to replace 7zr.osx to the client folder 7zr.

**Comment by winxp5421** [comment]
Alright so using this on OSX is not a straight forward as linux and windows as Hashcat does not come with pre-compiled binaries for OSX.

1. Did you compile your binarys for OSX?
2. If you did not compile your own Hashcat.net does not have OSX binarys hosted you need to compile these yourself.
3. After you compile these yourself you need to pack and host your own version of hashcat-3.50 to give to your clients.

have you done all of this?

**Comment by diamond2k** [comment]
:O 
None of them... Actually i hosted https://hashcat.net/files/hashcat-3.5.0.7z on my own lan.domain for the clients. But i have no idea how to compile and make it done. i will need to research this

**Comment by winxp5421** [comment]
Yes, hashcat does not come with OSX binaries. you will need to compile these.

However this issue does bring an issue to light with the cli command issued to the 7zr binary.

**Comment by diamond2k** [comment]
can you give some links to read about compiling hashcat to osx?
sorry i am bit new to osx, this would be experimental purpose, only couple weeks ago i could passed through successfully gpu to sierra vm.

**Comment by winxp5421** [comment]
I loath OSX so no i cant personally point you in the correct direction. There are some others that are more adept in the white crap box. maybe they will help you out.

**Comment by diamond2k** [comment]
u see thats also a challenge to make stronger vm than a latest whitebox pro, as u can see i also doesnt have physical mac

**Comment by diamond2k** [comment]
anyway i need to get work hashcat first

**Comment by soxrok2212** [comment]
https://github.com/hashcat/hashcat/blob/master/BUILD.md

Literally in the Hashcat readme.

**Comment by diamond2k** [comment]
thanks, hashcat has been compiled

**Comment by diamond2k** [comment]
Hiddens-Mac:hashcat hiddenhelper$ ./hashcat -b -m 2500
hashcat (v3.5.0-18-g086a0726) starting in benchmark mode...

OpenCL Platform #1: Apple
=========================
* Device #1: Intel Core 2 Duo P9xxx (Penryn Class Core 2), skipped.
* Device #2: ATI Radeon HD 5770, 256/1024 MB allocatable, 10MCU

Hashtype: WPA/WPA2

Speed.Dev.#2.....:    26848 H/s (93.92ms)

Started: Tue Apr 25 02:04:44 2017
Stopped: Tue Apr 25 02:04:59 2017

**Comment by diamond2k** [comment]
replaced fresh compiled hashcat folder in hashtopussy folder and it works !!!
Thank you @winxp5421 @soxrok2212

**Comment by winxp5421** [comment]
We will push a fix for whatever is going on with 7zr soon
