### ISSUE TITLE
Increase the maximum hash length

### ISSUE THREAD

**Issue by gearhjunkie** [s3inlc/hashtopussy#184]
The length of NTLMv2 hashes captured in Lgandx's Responder is 617 characters but hashtopussy's 
 database only accept hashes up to 512 characters.  Please increase it to 617 characters or larger.

**Comment by silentbreaksec** [comment]
SPN hashes can exceed 2,000 characters. We've run into this issue as well.

**Comment by s3inlc** [comment]
I'm not sure if it makes sense to just extend the VARCHAR of the hash field to such large numbers only for one or two hash algorithms as I'm not sure if this affects performance for requests, especially as there is an index built over the column.
If you have some time, you could test the speed is affected when you for example use MD5 hashes with VARCHAR length of the hash column to 2000 or something large.

**Comment by Console** [comment]
Just manually had to go in and bodge this one. Testing revealed that any SPN hash submitted out of the ones we're submitted from live environments (not just the hashcat example - that works fine, which lead to some major confusion) are all longer than the 1024 limit and get broken into chunks.

Raised the table column length to 4096 - I can deal with indexing/speed/performance issues right now, but I can't deal with non-functional cracking.

Then edited the values in hashtopussy/inc/handlers/HashlistHandler.class.php where buffers were set to 1024 to 4096.

Appears to give it enough headroom (Our SPN hashes are surfing around the 2500-2700 barrier depending on the username and domain associated with it) and cracking has resumed, this is most definitely a hacky bodge but it was needed in my case just to get it working.

**Comment by s3inlc** [comment]
The new version will allow setting the max length of hashes and plains via config page, so people don't have to change stuff directly on the sql server and everyone can set its required length.

**Comment by winxp5421** [comment]
Closing this issue it should be fixed with the new version.
