### ISSUE TITLE
Feature Request - Unused agents jump onto new tasks automatically.

### ISSUE THREAD

**Issue by phillips321** [s3inlc/hashtopussy#187]
Hashtopussy: commit 6e24570 branch master 0.3.2 - About

Is there a way we can get unassigned agents to automatically assign to new tasks? 

Thanks

**Comment by blazer2x** [comment]
I thought providing the task has a priority unused agents should automatically be assigned?

**Comment by winxp5421** [comment]
Indeed tasks which have a priority higher than zero should automatically issue agents to the tasks. Provided the agent is connected and in the "active" state.

Are we misunderstanding your Request?

**Comment by phillips321** [comment]
Ah apologies, didn't ever use the priority feature and didn't see it in the wiki so didn't know about it would auto assign. Thanks :-)
