### ISSUE TITLE
doc update

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#188]
Hey guys, it's not a bug report or anything, just wanted to let you know that in latest git release (I'm currently using commit 6e24570 branch master 0.3.2) is reporting following error and graphics are not rendering in admin panel (for example when looking at task status page/progress):
```
PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatetruecolor()
```

It's because missing php-gd library, so
```
apt update && apt install php-gd
```

and it's fixed. Just letting you know because I did not see this package on [Server Prerequisites](https://github.com/s3inlc/hashtopussy/wiki/Server-Prerequisites) nor [Installation](https://github.com/s3inlc/hashtopussy/wiki/Installation) wiki pages.

**Comment by s3inlc** [comment]
Thanks for letting us know this, I added the missing module to the server prerequisites.
