### ISSUE TITLE
Import pre-cracked hashes feature is broken?

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#190]
Hi again :-)

First thing first:
```
hashtopussy:        commit 6e24570 branch master 0.3.2
hashtopussy client: 0.43.13
hashcat:            3.5.0
```

Now the problem description.

I was working on list m.txt, about 29k hashes. I knew there are some duplicates in my already cracked Pre-cracked_16_12-05-2017_21-34-51.txt list (for example f357ac6d178921ad56110af378e463d5) so I tried to import it as pre-cracked ones. Then hashtopussy went into some kind of loop, import never finished and when I looked at overal cracked hashes count in m.txt list there was like 156k :-) It happened before with another hashlist, but I thought it was my mistake, but actually it is happening every time I'm importing big lists. Not sure what could be wrong here? I tried importing with and without option 'Overwrite already cracked hashes'. I was also using Upload and Import options under 'Hash source' option but there was no difference as well.

[both files attached](https://mega.nz/#!MZggXKjQ!6ubvm750gR-pr3E1JfBetAVUB8_TBg0Bt2VeOHrnHfw)

**Comment by winxp5421** [comment]
Hmm, we had another user in our inner circle report the same thing. at the time we were not sure what went wrong and shrugged it off as user error or one-time bug kinda thing. Now that you have reported the same general thing there might be something to this. Thanks we will have a look into it.

**Comment by Console** [comment]
Have had similar behaviour here. Worked with a small file but a large file of approximately 20,000 hashes pre-cracked against a 98,000 long hashlist, took forever to process, never returned to the page, but opening a new session and viewing the hashlist page revealed the results were showing as 130%+ complete and a negative number of hashes to crack.

Both with and without overwriting hashes ticked.

**Comment by s3inlc** [comment]
So this happens every time you try it with the same hashlist and the same file?

Would you mind providing us these two files so we can test it and search for the reason why it's hanging?

**Comment by d2-d2** [comment]
@s3inlc when I was testing it was happening every time with large lists. Check out my initial post and provided link. There are lists included.

**Comment by s3inlc** [comment]
Issue is resolved. It was not a looping issue, but the cracked of the hashlist was not updated correctly. Importing pre-cracked hashes is not a very fast process, there is some optimization needed. Generally I recommend at least ```sort -u``` such a list before importing to don't waste time because hashes are in the file multiple times.

Please check if the fix also works on your system @d2-d2 and close this issue.

**Comment by d2-d2** [comment]
Hey @s3inlc I have tested with latest commit

```
Hashtopussy: commit a512aec branch master 0.4.0
```

Using the same package of hash/cracked entries I was able to complete process of importing pre-cracked hashes.

```
Processed pre-cracked hashes: 99006 total lines, 11024 new cracked hashes, 8349 were already cracked, 0 invalid lines, 79633 not matching entries (845s)!
```

Good work. Thanks for fixing this issue!
