### ISSUE TITLE
A thought on Mask file and increment support

### ISSUE THREAD

**Issue by niels1189** [s3inlc/hashtopussy#191]
This is just a train of thought and suggestion, no need to take this as a 'MUST HAVE NOW' request to reject.

First things first, I am fully aware why mask files and increments aren't supported by hashtopussy.
But hear this out.

What if you create a separate upload spot, similar to what's done with the rules.
Once a file is uploaded it will create a 'mask task'. It would act similar to a pre-config supertask.
Meaning you have a 1000 task supertask that functions the same way as 1000 separate tasks. However, it is still controllable. 

Same could be done with increments.
Once someone adds a -i tag, you could add X tasks in a supertask that will increment from ?1 to ?1?1?1?1 for example.

Let me know what you think about this.
Don't take coding effort into consideration for this, I know it's a lot of work to implement something like this.

**Comment by winxp5421** [comment]
#116 #122
