### ISSUE TITLE
Server not dispatching task to agents

### ISSUE THREAD

**Issue by silentbreaksec** [s3inlc/hashtopussy#194]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.3.2

Current Client version.
0.43.17

The exact task command you are trying to run.
-a 0 #HL# rockyou.txt -r InsidePro-PasswordsPro.rule

Debug output from the client by running "hashtopussy.exe debug"
Getting task
{"action":"task","token":"temm8gGINh"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent

Describe your problem in as much detail as possible " It's broke " is not a description.
I just upgraded to the latest version of Hashtopussy, and the server isn't dispatching task data to the agents. The agents are connecting successfully, but the debug output show they aren't actually receiving any data. I can manually go in and assign an agent to a task, but then the agent switches back to unassigned after a couple seconds...in fact the agent seems to switch back to unassigned after the it makes a callback.

**Comment by winxp5421** [comment]
Just a double check. 1. is you agents in the active state "agents.php" and 2. is your agent trusted with "private" files?

**Comment by silentbreaksec** [comment]
Good grief...the trusted agent checkbox wasn't checked! Thanks for the speedy response and great tool.

**Comment by winxp5421** [comment]
your welcome glad it was an easy fix :)
