### ISSUE TITLE
Pre-import does not work with WPA hash type

### ISSUE THREAD

**Issue by mastercracker1** [s3inlc/hashtopussy#198]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage: **commit 6e24570 branch master 0.3.2**

Current Client version. **0.43.13**

The exact task command you are trying to run. **Pre-import via paste: 6cca084614f0:bc307d6535ed:ATT208:7165462839**

Debug output from the client by running "hashtopussy.exe debug": **Does not apply**

Describe your problem in as much detail as possible " It's broke " is not a description.:

**Trying to import pre-crack from WPA hash type is not working.  When I enter the essid with password like : "6cca084614f0:bc307d6535ed:ATT208:7165462839" (via paste), it says that it's not matching entries.  Changing the separator to something else in the pre-import form (and the paste value) does not change the end result either.  I have checked in the SQL table and the essid value really is "6cca084614f0:bc307d6535ed:ATT208" in the hashbinary table.  I have the feeling that it's because the value entered in the SQL database include : and the separator is usually that too so it might try to match only 6cca084614f0 against the full entry.**

**Comment by s3inlc** [comment]
Thanks for submitting this issue.
Generally when using pre-import of cracked hashes, the founds are always matched with the hashes. The special case in WPA where not the hash is used but the ESSID this case was not handled so far. 
This should be handled correctly now.
