### ISSUE TITLE
Integer overflow in keyspace

### ISSUE THREAD

**Issue by phillips321** [s3inlc/hashtopussy#200]
```
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
Server has requested the client to measure the keyspace for this task
Integer overflow detected in keyspace of mask: ?a?a?a?a?a?a?a?a?a?a
Getting task
```

hashcat 3.50

Hashtopussy: commit 6e24570 branch master 0.3.2

NTLM (12,000 hashes)

10char any doesn't work,
9char works fine
8char fine
...and so on

**Comment by winxp5421** [comment]
Sounds like you are running in a 32bit environment. 
If you feel this if false please check your php environment by running the PHP check script in the wiki frequent problems page https://github.com/s3inlc/hashtopussy/wiki/Frequent-Problems

**Comment by blazer2x** [comment]
Hi

Please see https://hashcat.net/forum/thread-6588-post-35071.html#pid35071

Seems like the overflow is a hashcat feature as it won't finish that attack in time with current hardware anyway.

**Comment by phillips321** [comment]
Blazer, sounds like the key mask is too large. Thanks for this. Was thinking it might be something to do with hashtopussy.

Mods, please close and mark as not a bug... (apologies)
