### ISSUE TITLE
Stuck checking for client updates

### ISSUE THREAD

**Issue by helloworldwh** [s3inlc/hashtopussy#215]
Server Version - 0.3.2
Client Version - 0.43.13
Hashcat Version - 3.6.0
task - mono ./hashtopussy.exe

See problem description for debug output

Problem Description - 
So here is my problem. I had my hashtopussy clients setup and running but I needed to switch the ubuntu boxes to static ip address. I did that and am able to ssh into them, access the internet, all that good stuff. But now when I run ```mono ./hashtopussy.exe``` it get stuck at "Checking for client updates". The only way I am able to make it work is to reinstall the hashtopussy client installation. Is there any way around this or is re-installation  the only way to make it work? Thanks in advance

**Comment by winxp5421** [comment]
Honestly, I don't even know where to begin with this as changing to static IP's should not effect hashtopussy clients in any way. 

Are you using a domain or direct IP ( ie. hashtopussy.domain.com or 192.168.0.0 )
Did you have to change the Hashtopussy server IP address to static as well is it different than your first install?
If you are using a domain do you have your DNS settings correct? you say you can access the internet so i would assume you could access the hashtopussy server as well.

**Comment by helloworldwh** [comment]
Sorry, dont know much about IP's. Here is what I can tell you. I changed the hashtopussy server installation's IP address to static as well. I can access the hashtopussy page by going to the server IP and that works fine(So yes, it is different than the first install...maybe this is the problem? The clients may not know where to look?). All of the clients should have correct DNS settings as I am able to access the internet, ssh into them and I remember setting the DNS correctly. I am not using any domain's so I assume I am using the IP.

**Comment by winxp5421** [comment]
In the hashtopussy clients, working directory changes the contents of the file 'URL' to reflect your changes. If you change where the server "address" (ipaddress) is the clients have no idea where to look unless you tell them about the change.

**Comment by helloworldwh** [comment]
Thanks! You're magic. I don't know how I didn't see that.
