### ISSUE TITLE
Unable to Upload 15GB File

### ISSUE THREAD

**Issue by helloworldwh** [s3inlc/hashtopussy#216]
Server Version - 0.3.2
Client Version - 0.43.13
Hashcat Version - 3.6.0

Problem Description-
Hopefully this is the last issue I will be posting on here as this probably has a very simple fix that will make me feel like an idiot. I am attempting to upload a 15gb wordlist via the hashtopussy webpage but it never goes through(it just has an infinite loading wheel on the top of the tab) until I get an error page that says "[ip address] is currently unable to handle this request \n HTTP ERROR 500".  I have gone to ```sudo nano /etc/php/7.0/apache2/php.ini``` and have changed the following variables -
```memory_limit = 150000000000000000000000000000M```
```upload_max_filesize = 400000000000000000000000000000000000000000000000M```
```post_max_size = 400000000000000000000000000000000000000000000000000M```
```max_file_uploads = 2000```

after which I did -
``` sudo service apache2 restart```

Am I not upping the values above enough or is this another value I need to change or something I am just completely missing? Thanks!

**Comment by winxp5421** [comment]
Sweet baby Jesus, your "values" are certainly large enough, in fact, having a memory limit WAY WAY above your physical memory is rather dangerous. 

15GB is rather large to handle via PHP upload i would suggest compressing this file ( 7z is supported) or uploading by the Import method.

**Comment by helloworldwh** [comment]
Haha, yes, I thought so but I just wanted to make sure that wasn't causing it. I will of course move them back down soon. I will try what you have suggested and get back with how it worked. Thanks!

**Comment by winxp5421** [comment]
With large files >2GB i would shy away from using the web panel upload ( on any software really) you will have a much better experience using the import method for these kinds of files. URL download would also work for these.

**Comment by blazer2x** [comment]
Also. http://php.net/manual/en/info.configuration.php#ini.max-execution-time
Perhaps that might help

**Comment by helloworldwh** [comment]
Well, I spent about 2 hours trying to figure out how to either access a samba share via terminal on ubuntu server or mount a usb but I couldn't figure those out so I used 7z and got it down to 1.5gb and was able to upload it! Thanks again for your help

Also, just to double check, once I upload it as .7z can I just throw it in the hashcat command line or do I need to do something else first?

**Comment by winxp5421** [comment]
https://github.com/s3inlc/hashtopussy/wiki/Server-Manual

```
7-Zip archives when added will show the file extention as ".???" Hashtopussy does not know the name of the file inside of the archive so you must use the file name inside the archive in the task command line. Example: Wordlist.7z contains the file Wordlist.txt the command line will need to be manualy changed from Wordlist.??? to Wordlist.txt
```
