### ISSUE TITLE
Hashcat 64 stopped working

### ISSUE THREAD

**Issue by realuncanny** [s3inlc/hashtopussy#220]
Server version: 0.3.2 , Client version 0.43.13, hashcat version : 3.6.0
Command: -a0 #HL# wordlist.txt -r rule1.rule -r rule2.rule -r rule3.rule

When hashtopussy runs hashcat to measure keyspace for the task, hashcat64 stops working and crashes.

Running on Windows 10, 64bit. Running hashcat64.exe -b works without any crashes so i wouldnt suspect it being a hashcat problem.

**Comment by s3inlc** [comment]
Have you tried running the exact same command with hashcat directly?

Depending on your hardware and how large your rules are, it might crash because there are too many rule combinations.

**Comment by winxp5421** [comment]
Please follow the issue template. If you do not we are just taking wild guesses at your problem.

**Comment by d2-d2** [comment]
@realuncanny you are running hashcat with 3 different rules. It sometimes happens that HC run out of memory when trying to process extensive rule sets. Is it a case here?

**Comment by winxp5421** [comment]
Its been almost a week without a reply. I am closing this. Please re-open with "hashtopussy.exe debug" output as stated in the Issue template.
