### ISSUE TITLE
Yubikey OTP Login

### ISSUE THREAD

**Issue by djban** [s3inlc/hashtopussy#223]
@s3inlc 
Attached.
[src.zip](https://github.com/s3inlc/hashtopussy/files/1119163/src.zip)

INSERT INTO `Config` (`configId`, `item`, `value`) VALUES
(18, 'yubikey_id', 'id'),
(19, 'yubikey_key', 'key='),
(20, 'yubikey_url', 'http://api.yubico.com/wsapi/2.0/verify');

CREATE TABLE IF NOT EXISTS `User` (
`userId` int(11) NOT NULL,
  `username` varchar(50) COLLATE utf8_bin NOT NULL,
  `passwordHash` varchar(512) COLLATE utf8_bin NOT NULL,
  `email` varchar(512) COLLATE utf8_bin NOT NULL,
  `passwordSalt` varchar(512) COLLATE utf8_bin NOT NULL,
  `isValid` tinyint(11) NOT NULL,
  `isComputedPassword` tinyint(11) NOT NULL,
  `lastLoginDate` int(11) NOT NULL,
  `registeredSince` int(11) NOT NULL,
  `sessionLifetime` int(11) NOT NULL DEFAULT '600',
  `rightGroupId` int(11) NOT NULL DEFAULT '1',
  `yubikey` int(1) NOT NULL DEFAULT '0',
  `otp1` varchar(50) COLLATE utf8_bin NOT NULL,
  `otp2` int(50) NOT NULL,
  `otp3` int(50) NOT NULL,
  `otp4` int(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

**Comment by winxp5421** [comment]
Nice, wonderful addition. Would you be interested in submitting a Pull Request so you can get credit for your work?

**Comment by winxp5421** [comment]
Thank you! s3 will look you PR over and commit.
