### ISSUE TITLE
1000.00 H/s & 0.00 H/s - varying speeds. 

### ISSUE THREAD

**Issue by forensec** [s3inlc/hashtopussy#226]
Hi,

I've got 11 machines setup. 7 with 1060s and 4 with 960s. I'm running a Luks crack, so I'm not expecting huge speeds. 
However when I go to the Task Details > Assigned Agents. Only two are showing a speed above 0.
Two are 1000.00 H/s
other 9 are 0.00 H/s. 

However, they are saying they're working and have searched a tiny amounts of keyspace. 

Any ideas why this would be? Sorry it's not much detail. 

p.s The I'm unclear about what the "Benchmark" value means. For the two running at 1khs, their value was about 0.001.. + 0.0018.. the rest were super low at around 0.0000000001..etc. So I set all the ones with the 1060s to the same benchmark of 0.0018..

What's more when I run a hashcat benchmark on one of my 1060 machines I get 4076 H/s (6.24ms)

Help please!

**Comment by winxp5421** [comment]
Sounds like you may benefit from the runtime benchmark instead of using the speedtest benchmark for your particular task. Depending on the hash type or if you are running multiple hashes with salts the speedtest benchmark may not hand out proper chunk sizes resulting in very low performance. 

Copy your task and select runtime for your benchmark type. It may fix your distribution efficiency.

**Comment by forensec** [comment]
My task was already set to "Benchmark type: Runtime Benchmark". All I try Speed Test?
Also some of the machines went from 0 to 1kh/s and I think it happened after the first chunk had been dispatched and processed; the subsequent chuncks were running at 1kh/s. 


Another issue is that now the keyspace is 100% dispatched, some machines have finished their chunks and are now idle. I can't get these idle machines assigned to new tasks. The client keeps "Getting task", but then I refresh H2P and the agents have became unassigned again.

**Comment by winxp5421** [comment]
Alright so after those chunks completed your speed increased which confirms it is a chunk sizing problem.

Manually changing benchmark values is not advised as now you have Very large chunks for your machines and not enough keyspace to keep them all busy. 

Your idle agents should move to the next available task with a priority set. 

You can try the speed test benchmark though it is rather strange benchmarking with runtime did not give you good results.

**Comment by winxp5421** [comment]
House cleaning.
