### ISSUE TITLE
Email Notifications not working

### ISSUE THREAD

**Issue by helloworldwh** [s3inlc/hashtopussy#247]
Server version - 0.3.2
Client version - 0.43.13
hashcat version - 3.6.0
I have setup an email notification for just about every action that can happen yet I have not received any emails. All I did to "set it up" was enter my email and the action on the notifications page on the web ui. Is there somewhere else that I am supposed to configure the mail server or point it towards one?

**Comment by s3inlc** [comment]
The server should be configured to be able to send emails. Otherwise PHP cannot send the email with it's function.

http://php.net/manual/en/mail.requirements.php

**Comment by helloworldwh** [comment]
So, I reopened this because after installing sendmail, it's only halfway working. I will get an email when I create a new Task, a task finish etc etc but I do not get an email for the following - agentError, logError, logFatal, logWarn and ownAgentError. I have installed and configured sendmail on both the servers and the clients although I'm not sure how necessary it was for the clients.

**Comment by s3inlc** [comment]
I will go trough all notifications and test them to see if the same also don't work for me the next few days.

**Comment by s3inlc** [comment]
Ok, I went trough these notifications, let me list it:

* `logWarn` works
* `logError` works
* `logFatal` should work, but currently there is NO occurrence of it, so currently there will never be a notification issued with it.
* `ownAgentError` this notification was not implemented before, so it was also never executed. I fixed this now, so this notification should be possible to receive.

Generally, when you test it with email notifications, currently it's using a generic header, so it's possible that the email gets put into the spam folder, so please also check there.

**Comment by winxp5421** [comment]
Doing some house cleaning. Feel free to re-open if this is still a problem for you.

**Comment by sphereict** [comment]
Hey guys
first of all let me say thank you for an awesome app. This systems works great. 

I am however battling with sending mail notifications . I have installed postfix and did the required setup. 
I tested that I can send mail and it works.

I have setup hashtopolis to send notifications to me when a new task is created. I checked the logs with the tail command and can see nothing being send. I am not getting any notifications. 

Can you please help me with this. 

I am using latest hashtopolis 0.5.0-rc1

Sincerely.
Gerhard
