### ISSUE TITLE
Error 500 when trying to create new hashlist

### ISSUE THREAD

**Issue by glemercier** [s3inlc/hashtopussy#248]
Hashtopussy: commit da00d41 branch master 0.4.2

I'm getting a 500 error when clicking the "New hashlist" menu item, leading to http://localhost/hashlists.php?new=true.

I have a fresh installation of hashtopussy, everything else seems to run fine except that. I'm available to provide more specific log/debug information if needed.

**Comment by s3inlc** [comment]
Thanks for reporting this, there was a typo causing this error. Please try with the latest commit, it should be fixed.

**Comment by glemercier** [comment]
I confirm it works with the fix. Thanks a lot for the quick turnaround!
