### ISSUE TITLE
Tasks broken after upgrade

### ISSUE THREAD

**Issue by helloworldwh** [s3inlc/hashtopussy#250]
Server Version: 0.3.2
Client Version: 0.43.13
Hashcat Version: 3.6.0

Problem - So I just attempted to update from 0.3.2 to 4.0. I backed up the load.php and Encryption.class.php. There was nothing in "files" so I did not back it up. I followed the upgrade page restored the two backed up files and tried to run the upgrade scripts.  Here is what I get when I run it - 

```php -f update_v0.3.2_v0.4.0.php 
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 4
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 5
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 6
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 7
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 8
Apply updates...
Add new config... Fatal Error ! Database connection failed ```

On top of that, the Tasks page now no longer loads in the web UI and I get this error - 
```Fatal error: Uncaught Error: Call to undefined method Util::loadTasks() in /var/www/hashtopussy/tasks.php:317 Stack trace: #0 {main} thrown in /var/www/hashtopussy/tasks.php on line 317```

What did I mess up?

**Comment by winxp5421** [comment]
I believe the DB connection file was separated from load.php so upgrades can be handled better via git. If you have a look around where load.php is stored you should be able to find then issue. If not let me know all try and get a step by step to you.

On Aug 4, 2017, helloworldwh <notifications@github.com> wrote:

Server Version: 0.3.2
Client Version: 0.43.13
Hashcat Version: 3.6.0

Problem - So I just attempted to update from 0.3.2 to 4.0. I backed up the load.php and Encryption.class.php. There was nothing in "files" so I did not back it up. I followed the upgrade page restored the two backed up files and tried to run the upgrade scripts. Here is what I get when I run it -

PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 4
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 5
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 6
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 7
PHP Notice:  Undefined variable: CONN in /home/hashtopussy/hashtopussy/src/dba/init.php on line 8
Apply updates...
Add new config... Fatal Error ! Database connection failed ```

On top of that, the Tasks page now no longer loads in the web UI and I get this error -
```Fatal error: Uncaught Error: Call to undefined method Util::loadTasks() in /var/www/hashtopussy/tasks.php:317 Stack trace: #0 {main} thrown in /var/www/hashtopussy/tasks.php on line 317```

What did I mess up?

**Comment by winxp5421** [comment]
House cleaning, if you are still having issues please re-open.
