### ISSUE TITLE
Reset task priority

### ISSUE THREAD

**Issue by niels1189** [s3inlc/hashtopussy#253]
Not sure what caused this yet, but after a task is completed it seems to not only reset the priority of the task that's finished, but of every task.

**Comment by niels1189** [comment]
Correction: at random, not at end of task.

**Comment by s3inlc** [comment]
So you say at a random time it happens that all priorities get set to 0?
What kind of tasks have you set when this happens?

**Comment by niels1189** [comment]
Mask attacks on an MD5 wordlist. I'm still trying to find out what's causing it but no error logs are made.
No SQL errors.

**Comment by niels1189** [comment]
Alright, I'll keep an eye out. Fair chance that it's related to the new beta version (seeing as my other issue seems to be caused by the new client as well).

**Comment by s3inlc** [comment]
Please try with this beta binary and report back if it still happens:

https://github.com/s3inlc/hashtopussy-agent/blob/master/csharp/hashtopussy/binary/hashtopussy_beta.exe

**Comment by niels1189** [comment]
Downloading hashlists, I'll keep you updated.

**Comment by niels1189** [comment]
No change detected.

**Comment by niels1189** [comment]
I think it occurs after a chunk is completed.

**Comment by blazer2x** [comment]
We know what the issue is, if it's caused by a chunk. The client is reporting a status which is unknown to the server. Since the STATUS codes were changed, we can either apply a client or server-side fix. A client-side fix will be added this week for comparability to support both 3.6.0 and also > 3.6.0

**Comment by s3inlc** [comment]
@niels1189 have you tried with the new client version, does the problem still persists or was it caused by the status changes on the new beta of Hashcat?

**Comment by winxp5421** [comment]
Doing some house cleaning. We have not heard from you in 7 months. im going to assume your issue has been sorted.
