### ISSUE TITLE
Telegram bot notification

### ISSUE THREAD

**Issue by niels1189** [s3inlc/hashtopussy#255]
Might be nice to have this on the TODO list.
It's free and easy to set up after configuring a few parameters.

**Comment by s3inlc** [comment]
Does the current ChatBot notification type not have the right possibilities to use it for Telegram notifications?

**Comment by niels1189** [comment]
I don't think so. Couldn't find the relevant documentation for it explaining it's complete functionality.
Even the attempt at integrating it into slack is becoming a bit difficult.

**Comment by s3inlc** [comment]
With slack it should work, as long as you only have an url hook which can be entered as receiver.
But I have to look into how Telegram bots should be addressed.

**Comment by niels1189** [comment]
Any documentation on how to aquire a hook url. Can't seem to find how.
Unless it involves making an entire bot around it,
