### ISSUE TITLE
Error when adding  a new notification

### ISSUE THREAD

**Issue by NullPatrol** [s3inlc/hashtopussy#258]
After adding a chatbot with any value:

syntax error, unexpected ',', expecting ';' in /var/www/html/inc/templating/Statement.class.php(181) : eval()'d code on line 1

Invalid argument supplied for foreach() in /var/www/html/hashtopussy/inc/templating/Template.class.php on line 38

**Comment by s3inlc** [comment]
Issue should be fixed now.
Please close this when it's also fixed for you.

**Comment by NullPatrol** [comment]
First one fixed.
Second error is still an issue.

**Comment by NullPatrol** [comment]
Seems to be when the notification is called, although this might be related to me adding an new 'type' of notification type.

**Comment by s3inlc** [comment]
What kind of notification did you try to add?
What value did you enter as a receiver?

**Comment by NullPatrol** [comment]
Fixed: Missing template

**Comment by s3inlc** [comment]
Thanks for the feedback.
