### ISSUE TITLE
Plaintext too long - parsing error

### ISSUE THREAD

**Issue by NullPatrol** [s3inlc/hashtopussy#261]
I cracked a bunch of hashes away from hashtopussy with random masks and ended up with 1.2M founds that I tried to upload. But when uploading I received a 500 error.

It's 1,212,19 hashes so I'm not sure how I'm going to check what's exactly wrong.
But none of them exceed 90 chars in length (including the md5 string)

PHP Error Log:
`PHP Notice:  Undefined offset: 1 in /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php on line 740, referer: http://192.168.178.12/hashtopussy/hashlists.php?id=1
PHP Notice:  Undefined offset: 1 in /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php on line 740, referer: http://192.168.178.12/hashtopussy/hashlists.php?id=1
PHP Notice:  Undefined offset: 1 in /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php on line 740, referer: http://192.168.178.12/hashtopussy/hashlists.php?id=1
PHP Notice:  Undefined offset: 1 in /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php on line 740, referer: http://192.168.178.12/hashtopussy/hashlists.php?id=1
PHP Notice:  Undefined offset: 1 in /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php on line 740, referer: http://192.168.178.12/hashtopussy/hashlists.php?id=1
PHP Notice:  Undefined offset: 1 in /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php on line 740, referer: http://192.168.178.12/hashtopussy/hashlists.php?id=1

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'plaintext' at row 1 in /var/www/hashtopussy/dba/AbstractModelFactory.class.php:200
Stack trace:
#0 /var/www/hashtopussy/dba/AbstractModelFactory.class.php(200): PDOStatement->execute(Array)
#1 /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php(731): DBA\\AbstractModelFactory->update(Object(DBA\\Hash))
#2 /var/www/hashtopussy/inc/handlers/HashlistHandler.class.php(73): HashlistHandler->processZap()
#3 /var/www/hashtopussy/hashlists.php(33): HashlistHandler->handle('processZap')
#4 thrown in /var/www/hashtopussy/dba/AbstractModelFactory.class.php on line 200`

**Comment by NullPatrol** [comment]
2991349652a2360156069f75e9??????:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Replaced a few characters as I don't think it's releated.
But I also got a 500 error trying to import this one.
One X and one ? equal 1 character length wise.

**Comment by NullPatrol** [comment]
Looks like this occurs with every hash I tried to upload.

**Comment by s3inlc** [comment]
Thanks for pointing out the PHP warnings, they are not related with the real issue here, but I fixed this.

This problem seems to be really strange. Technically the limit for plaintexts currently is at 200 chars, so 90 should definitely not be a problem. I'll try to reproduce the error.

**Comment by NullPatrol** [comment]
I'll try to update some of my source code to GitHubs' most recent version.

**Comment by NullPatrol** [comment]
Updated all files, no change in result.

**Comment by NullPatrol** [comment]
One of the plaintexts I tried to upload was 225 characters long from what I can see. 
it was not stored in the sql database. It wasn't truncated either.
I think it might still be stored somewhere (trying to find it).

**Comment by NullPatrol** [comment]
Bug found.
Issue: No handling for plaintexts over 200 characters (in zaplists).
System tries to process the zaplist, but can't because a string is over 200 characters.

How to reproduce:
Upload a file or hash:plaintext where at least one plaintext contains over 200 characters.

How to resolve:
Remove the 200+ char hash from /tmp/zaplist_x

**Comment by s3inlc** [comment]
In such situations it's always the question to what length something like this should be limited. 
I can adjust it, so it doesn't crash on a plain which is longer than the limit, so the import doesn't get aborted.

**Comment by NullPatrol** [comment]
I think a good solution would be to parse everything but the plains longer than that limit.
Throw an error saying X plains were not inserted because they exceeded a length of {{ limit }}

**Comment by s3inlc** [comment]
Yes that's what I thought too. This way all the other plains will be imported without problems and the user gets notified that some were too long.
This was the reason I labelled it as enhancement.
