### ISSUE TITLE
Key Not Found Exception

### ISSUE THREAD

**Issue by Lantern1995** [s3inlc/hashtopussy#263]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.4.2
Current Client version
0.43.19
Your current Hashcat version
3.40
The exact task command you are trying to run.
a supertask, containing an hmask file
Debug output from the client by running "hashtopussy.exe debug"
Client Version 0.43.19
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.19"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"D21ZKrUHm7"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"D21ZKrUHm7","force":0}
Hashcat version v3.40 found
Getting task
{"action":"task","token":"D21ZKrUHm7"}
{"action":"task","response":"SUCCESS","task":16,"attackcmd":"-a3 #HL# ?a?a?a?a?a?a?a?","cmdpars":" --hash-type=0","hashlist":7,"bench":30,"statustimer":5,"files":[],"benchType":"run","hashlistAlias":"#HL#"}
Server has assigned client with Task:16 and Hashlist:7
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"D21ZKrUHm7","hashlist":7}
Getting chunk...
{"action":"chunk","token":"D21ZKrUHm7","taskId":16}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using C:\Users\EX\Downloads\files\ as working directory
C:\Users\EX\Downloads\hashcat\hashcat64.exe   --hash-type=0 -a3  ?a?a?a?a?a?a?a? --session=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"D21ZKrUHm7","taskId":16,"keyspace":81450625}
Getting chunk...
{"action":"chunk","token":"D21ZKrUHm7","taskId":16}
{"action":"chunk","response":"SUCCESS","status":"benchmark"}
Using C:\Users\EX\Downloads\files\ as working directory
C:\Users\EX\Downloads\hashcat\hashcat64.exe  --hash-type=0 -a3 "C:\Users\EX\Downloads\hashlists\7" ?a?a?a?a?a?a?a? --runtime=30 --restore-disable --potfile-disable  --machine-readable --session=hashtopussy --weak=0
Server requsted the client benchmark this task for 30 seconds

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at hashtopussy.taskClass.getChunk(Int32 inTask)
   at hashtopussy.taskClass.getTask()
   at hashtopussy.Program.Main(String[] args)

Describe your problem in as much detail as possible " It's broke " is not a description.

Problem 1) Trying to mask attack a hashlist, but whenever a client fetches or tries to fetch a task, it instantly crashes. my current Hashtopussy server is on a ubuntu VM that has port forwarding from the host (on port 80).
 
My first option: running the hashtopussy server on a dedicated machine instead of a VM, so that the agents can communicate with it and "see" it through all ports, not just 80 (which is forwarded from the host)

Problem 2) Mask attack through a normal task does not work, its either too big or too small, integer overflow or keyspace is too small.

My first option: running supertasks to bruteforce, but that leads me back to key was not found in the dictionary

**Comment by s3inlc** [comment]
Can you please run the benchmark command directly on the agent the error happened and post the output here?

```
C:\Users\EX\Downloads\hashcat\hashcat64.exe --hash-type=0 -a3 "C:\Users\EX\Downloads\hashlists\7" ?a?a?a?a?a?a?a? --runtime=30 --restore-disable --potfile-disable --machine-readable --session=hashtopussy --weak=0
```

**Comment by s3inlc** [comment]
Problem 1)
How the client is crashing? Is it because he tries to retrieve things from a wrong url because the server is behind the NAT?
Normally there should be no problem with just using port 80, there is no need of any other port.

**Comment by Lantern1995** [comment]
Thank you for your quick reply :)

I've went back and tracedback all my steps, and suddenly, everything works, i'm cracking now on 2 systems. still using the port forwarding method. 

However, I have some questions/concerns,
I'm trying to crack on my 2 systems, however 1 system hogs all the task, and the other just sits idley
![agents3](https://user-images.githubusercontent.com/31035093/29317498-119be516-81c4-11e7-88de-d6d338a092e8.PNG)

![undistrubuted](https://user-images.githubusercontent.com/31035093/29317510-1d3d329e-81c4-11e7-9c86-086d5c612ea3.PNG)

as you can see, the cracking is going well and underway! however, its a single mask 7 character long mask attack on an md5 hash, is that why it can't be distributed?

Do I have to start a super task?

![undisturbutedddddd](https://user-images.githubusercontent.com/31035093/29317541-47074254-81c4-11e7-8cf7-0b5225efa9c7.PNG)

**Comment by s3inlc** [comment]
With just this normal task, both agents should work on it, as long as it is not fully dispatched. But what I see from the agents screenshot, for some reason the second agent is inactive. So you have to set the tick for making it active again, and as long as there are not errors appearing, it then should also start cracking.

**Comment by Lantern1995** [comment]
Yes, it worked! thank you! trying it now on my cracking rigs

**Comment by s3inlc** [comment]
Just a general comment, I recommend to use the newest Hashcat and also the newest Hashtopussy Agent binary.

**Comment by winxp5421** [comment]
House cleaning, Please re-open if you still require help.
