### ISSUE TITLE
Generate voucher by API

### ISSUE THREAD

**Issue by FinlayDaG33k** [s3inlc/hashtopussy#274]
Hi there,

I'm trying to modify the Hashtopussy Agent, and I was wondering: is there a way to generate a voucher by sending a command to the HTTP server?

I want to distribute my Agents to some friends (in a completely legal manner, even though you've probably heard that story before lol).
However, I do not want to have to create vouchers by hand all the time.

So yea, is there a way to do so? :)

Cheers

**Comment by s3inlc** [comment]
Currently this is not possible. If you really need this, you can just comment out this line: https://github.com/s3inlc/hashtopussy/blob/master/src/inc/API.class.php#L487

This would keep a created voucher and it can be used multiple times then.

**Comment by FinlayDaG33k** [comment]
Guess I'll stick to that for now.
