### ISSUE TITLE
Notice: Undefined index: after upgrade

### ISSUE THREAD

**Issue by rfrogman** [s3inlc/hashtopussy#277]
Hashtopussy: 0.4.2
Client: 0.43.19
Hashcat: 3.6.0

Server is Ubuntu 16.10 64bit

After following upgrade instruction in your wiki from 0.3.2 to 0.4.0. The update script reported everything OK and now we are receiving the following errors. (we set debug to "1" in load.php)

hashlist.php
Notice: Undefined index: hashlistId in /var/www/hashtopussy/dba/models/HashlistFactory.class.php on line 36
Notice: Undefined index: hashTypeId in /var/www/hashtopussy/dba/models/HashTypeFactory.class.php on line 36

task.php
Notice: Undefined index: taskId in /var/www/hashtopussy/dba/models/TaskFactory.class.php on line 36
Notice: Undefined index: hashlistId in /var/www/hashtopussy/dba/models/HashlistFactory.class.php on line 36

Our previous tasks and hashlists data is still in the database

**Comment by s3inlc** [comment]
Can you please check that all the files were updated to the latest commit from the repository (especially the ones in the `dba` folder).

**Comment by rfrogman** [comment]
After re-downloading tar ball from github, we have recopies the files into /dba folder, verified permission and owner, and restarted services. Receiving same error on task.php and hashlist.php. The rest of the site appears to be working. I can get to a specific tasks if I click the link for past chunks but receive the errors if I try to show tasks or show hashlists. If  I try to use the link from a task to view a hashlist I receive "Invalid hashlist". I have also verified that the correct changes have been applied in the database from the update0.3.2-0.4.0 script.

**Comment by rfrogman** [comment]
OK, I guess third time is a charm. I have resolved the issue by downloading the zip "hashtopussy-master". Evidently we used the "hashtopussy-0.4.2" download which must have had something different in dba/. We can now view task.php and hashlist.php.
