### ISSUE TITLE
Problem importing HCCAPX files

### ISSUE THREAD

**Issue by xscode** [s3inlc/hashtopussy#279]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.4.2
Current Client version
0.45.9
Your current Hashcat version
3.6.0
The exact task command you are trying to run.
#HL# --markov-disable -a3 -1d ?1?1?1?1?1?1?1?1
Debug output from the client by running "hashtopussy.exe debug"
Client Version 0.45.9
Connecting to server http://192.168.0.20/hashtopussy/api/server.php
Checking for client updates
{"action":"update","type":"csharp","version":"0.45.9"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Linux
Existing token found
{"action":"login","token":"tRSoNc1RlI"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"tRSoNc1RlI","force":0}
Hashcat version v3.6.0 found
Using legacy STATUS codes
Getting task
{"action":"task","token":"tRSoNc1RlI"}
{"action":"task","response":"SUCCESS","task":1,"attackcmd":"#HL# --markov-disable -a3 -1d ?1?1?1?1?1?1?1?1","cmdpars":" --hash-type=2500","hashlist":1,"bench":30,"statustimer":5,"files":[],"benchType":"run","hashlistAlias":"#HL#"}
Server has assigned client with Task:1 and Hashlist:1
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"tRSoNc1RlI","hashlist":1}
Getting chunk...
{"action":"chunk","token":"tRSoNc1RlI","taskId":1}
{"action":"chunk","response":"SUCCESS","status":"benchmark"}
Using /home/stuart/files/ as working directory
/home/stuart/hashcat/hashcat64.bin  --hash-type=2500 "/home/stuart/hashlists/1" --markov-disable -a3 -1d ?1?1?1?1?1?1?1?1 --runtime=30 --restore-disable --potfile-disable  --machine-readable --session=hashtopussy --weak=0
Server requested the client benchmark this task for 30 seconds
No hashes loaded.

Unhandled Exception:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <8f2c484307284b51944a1a13a14c0266>:0 
  at hashtopussy.taskClass.getChunk (System.Int32 inTask) [0x004e7] in <4ff82483e5054dd0b4a2dfa86aa2b116>:0 
  at hashtopussy.taskClass.getTask () [0x00311] in <4ff82483e5054dd0b4a2dfa86aa2b116>:0 
  at hashtopussy.Program.Main (System.String[] args) [0x00275] in <4ff82483e5054dd0b4a2dfa86aa2b116>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <8f2c484307284b51944a1a13a14c0266>:0 
  at hashtopussy.taskClass.getChunk (System.Int32 inTask) [0x004e7] in <4ff82483e5054dd0b4a2dfa86aa2b116>:0 
  at hashtopussy.taskClass.getTask () [0x00311] in <4ff82483e5054dd0b4a2dfa86aa2b116>:0 
  at hashtopussy.Program.Main (System.String[] args) [0x00275] in <4ff82483e5054dd0b4a2dfa86aa2b116>:0 

Describe your problem in as much detail as possible " It's broke " is not a description.
All other hash types i've tried work fine but HCCAPX files don't seem to be parsed correctly on upload (see attached image of entries in DB).  
![hashes](https://user-images.githubusercontent.com/6640911/30005306-367885e8-90d7-11e7-8987-9922ed50b4c2.jpg)

**Comment by winxp5421** [comment]
Its tough to tell which table these are located in on your screen shot. but seen as i see Hex hashes on the top two lines. Im willing to bet you uploaded these HCCAPX files as standard hash lists and not as a binary file. Re-upload the HCCCAPX files as binary hashlists.

**Comment by winxp5421** [comment]
![image](https://user-images.githubusercontent.com/7359229/30005477-0eb2cd94-90a9-11e7-8aef-a6678143e8f0.png)

**Comment by xscode** [comment]
Ahhhh!, apologies for missing this.  I've now uploaded a file and it has imported correctly into the hashbinary table correctly but i cannot get either of my 2 agents to be assigned.  No matter where I assign them withing h2p a refresh a few seconds later shows them de-assigned?.

**Comment by s3inlc** [comment]
Is there anything on the clients shown when they automatically get unassigned?

**Comment by winxp5421** [comment]
Verify trusted/ untrusted status as well.

**Comment by xscode** [comment]
All trusted and assigned an owner.  Priority set at 100.
One client tried briefly to benchmark but then...

Downloading hashlist for this task, please wait...
{"action":"hashes","token":"tRSoNc1RlI","hashlist":2}
{"action":"hashes","response":"SUCCESS","data":"SENQWAQAAAAAC0JUSHViNS1GODU3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAuGYnpJ7oAGG+ewePgjMlInIkflYyuUlL5cPimCjSrDM4pYML\/NCme2Fb+THIKmrXKYu1DNbBLDFWT7VEARwwPBnEYZFLKtOiGH90d4QbCU0fzp2+u1nMsoAdaDkeQABAwB1AgEKAAAAAAAAAAAAAQRwwPBnEYZFLKtOiGH90d4QbCU0fzp2+u1nMsoAdaDkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYwFAEAAA+sBAEAAA+sBAEAAA+sAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASENQWAQAAAACC0JUSHViNS1GODU3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAuGYnpJ7oAGG+ewePgjMlInIkflYyuUlL5cPimCjSrDM4pYML\/NCme2Fb+THIKmrXKYu1DNbBLDFWT7VEARwwPBnEYZFLKtOiGH90d4QbCU0fzp2+u1nMsoAdaDkeQABAwB1AgEKAAAAAAAAAAAAAQRwwPBnEYZFLKtOiGH90d4QbCU0fzp2+u1nMsoAdaDkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYwFAEAAA+sBAEAAA+sBAEAAA+sAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}
Getting chunk...
{"action":"chunk","token":"tRSoNc1RlI","taskId":6}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using /home/stuart/files/ as working directory
/home/stuart/hashcat/hashcat64.bin   --hash-type=2500 -a 3  ?l?l?l?l?l?l?l?l --session=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"tRSoNc1RlI","taskId":6,"keyspace":8031810176}
Getting chunk...
{"action":"chunk","token":"tRSoNc1RlI","taskId":6}
{"action":"chunk","response":"ERROR","message":"You are not assigned to this task!"}
ERROR
You are not assigned to this task!
Getting task
{"action":"task","token":"tRSoNc1RlI"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent

**Comment by winxp5421** [comment]
Can we get a screen shot of client details page as well as the tasks.php and detail view of the task in question

**Comment by xscode** [comment]
![hashtopussy 0 4 2 192 168 0 20 - google chrome_003](https://user-images.githubusercontent.com/6640911/30005755-6501a020-90e1-11e7-9ad9-1384c86d00c6.jpg)
![hashtopussy 0 4 2 192 168 0 20 - google chrome_002](https://user-images.githubusercontent.com/6640911/30005757-6eb173ca-90e1-11e7-8b15-feebec718789.jpg)

Trying a different HCCAPX with problems causes the client to infinitely do...
Getting chunk...
{"action":"chunk","token":"xORkckCxSw","taskId":8}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using /home/stuart/hash2pussy/files/ as working directory
/home/stuart/hash2pussy/hashcat/hashcat64.bin   --hash-type=2500 -a3  -1NBMYWPFCDVXTLRSQ ?1?1?1?1?1?1?1?1?1L --session=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"xORkckCxSw","taskId":8,"keyspace":4294967296}
Getting chunk...
{"action":"chunk","token":"xORkckCxSw","taskId":8}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using /home/stuart/hash2pussy/files/ as working directory
/home/stuart/hash2pussy/hashcat/hashcat64.bin   --hash-type=2500 -a3  -1NBMYWPFCDVXTLRSQ ?1?1?1?1?1?1?1?1?1L --session=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"xORkckCxSw","taskId":8,"keyspace":4294967296}
Getting chunk...
{"action":"chunk","token":"xORkckCxSw","taskId":8}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using /home/stuart/hash2pussy/files/ as working directory
/home/stuart/hash2pussy/hashcat/hashcat64.bin   --hash-type=2500 -a3  -1NBMYWPFCDVXTLRSQ ?1?1?1?1?1?1?1?1?1L --session=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"xORkckCxSw","taskId":8,"keyspace":4294967296}
Getting chunk...

Thanks for your help guys

**Comment by s3inlc** [comment]
I currently cannot see what the problem is. But it looks like it can't save the keyspace value. 
Can you check what PHP version is running on the server? If it's 32bit I think the large keyspace number is the problem as it doesn't fit into a 32bit integer.

**Comment by xscode** [comment]
php 5.6 running on a Synology 216j (Marvell Armada 385) so i think you may be right.  Might be better for me to ressurect an old 64bit laptop as a server.

**Comment by s3inlc** [comment]
Ok, generally there is not really much which can be done when only 32bit PHP is available. A lot of the numbers in Hashcat and related parts have numbers which really require 64bit integers.
