### ISSUE TITLE
Error 500 when exporting wordlist or pre-cracked

### ISSUE THREAD

**Issue by irishmike** [s3inlc/hashtopussy#282]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.4.2

Current Client version
0.45.8

Your current Hashcat version
v3.6.0

The exact task command you are trying to run.
Any attempt to use the options under "Actions" in hashlist details

Debug output from the client by running "hashtopussy.exe debug"
N/A

Describe your problem in as much detail as possible " It's broke " is not a description.
I receive a 500 error in my browser (any browser) when using the buttons to export anything when the hashlist is WPA(2) from an hccapx file. I have checked permissions and they are as required by installation. Please advise.

**Comment by s3inlc** [comment]
Can you please set the PHP ini variable `display_errors`to `1` and then do the same action again. This should display the error then, post this here then.

**Comment by irishmike** [comment]
It still only displays an error 500 in the browser with no additional information.

Is there a log I should be looking at?

Thank you!!!

**Comment by s3inlc** [comment]
That's strange that you don't get any information on the error. Did you turn the display errors on in the .ini file or directly in `inc/load.php`?

**Comment by NullPatrol** [comment]
Perhaps if you send us the /var/log/apache2/error.log details you can receive more help.

**Comment by winxp5421** [comment]
We have not heard from you in a while. Please re-open if you still need help.
