### ISSUE TITLE
append some "h2" info to page "title" tag

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopussy#283]
(Server version: 0.4.2)

It would be nice if each page had the de-facto page title (in the h2 tag) appended to the contents of the title tag, as in:

Hashtopussy 0.4.2 [servername] - Task details
Hashtopussy 0.4.2 [servername] - Add new agent

... etc. This would be handy when looking at browser history or back-button choices, as well as for bookmarks.

As a later or if-you-have-time additional improvement, if the page is about a single specific element (such as task details, it would be nice to include that as well, as in:

Hashtopussy 0.4.2 [servername] - Task details for #blah (taskname)
Hashtopussy 0.4.2 [servername] - Agent details for #blah (machine name)
Hashtopussy 0.4.2 [servername] - Hashlist details for #blah (hashlist name)
Hashtopussy 0.4.2 [servername] - User (username)

... etc.

**Comment by s3inlc** [comment]
Detailed page titles are added to the currently developed version.

**Comment by roycewilliams** [comment]
Very handy - thanks very much!
