### ISSUE TITLE
feature: configurable sent-email options

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopussy#284]
It would be nice to be able to customize some aspects of the sent email:

- The "From" name and sending domain (currently "Hashtopussy" and "noreply@hashtopussy")

- The subject line is always generic - would be nice for it to include the broad category name of the notification (agentError, deleteAgent, etc.)

**Comment by s3inlc** [comment]
The sending email for all kind of emails from the server can be adjusted in the config in the upcoming version. Do you think it is really necessarily to also set the senders name? If yes, it can also be added as a config value.
I will care about the subject line to contain information about which kind of notification.

**Comment by roycewilliams** [comment]
Sweet!

Yep, sender's name would be good - even if a generic/role one. Having this set will avoid a couple of SpamAssassin-based filtering heuristics. It will also allow emails from multiple clusters to be differentiated in various MUAs.

**Comment by s3inlc** [comment]
Ok, I get your point. I'll include these changes in the upcoming version.

**Comment by s3inlc** [comment]
Notifications are now sent with a informative subject line.

**Comment by roycewilliams** [comment]
Looks great - thanks!
