### ISSUE TITLE
include text MIME part in notification emails

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopussy#285]
(Server version: 0.4.2)

Notification emails are crafted solely as HTML, without a text-only mime part. This causes some SpamAssassin-based spam filtering systems to bump up the spam score a bit (the "HTML_MIME" and "MIME" hits below):

```
X-Spam-hits: BAYES_20 -0.001, HEADER_FROM_DIFFERENT_DOMAINS 0.001, HTML_MESSAGE 0.001,
  HTML_MIME_NO_HTML_TAG 0.377, ME_NOAUTH 0.01,
  MIME_HEADER_CTYPE_ONLY 0.717, MIME_HTML_ONLY 0.723,
  RCVD_IN_DNSWL_LOW -0.7, RP_MATCHES_RCVD -0.001, LANGUAGES unknown,
  BAYES_USED global, SA_VERSION 3.4.0
```

**Comment by s3inlc** [comment]
Please check if the updated email now applies with your idea. All emails should now be sent with a plaintext and a html content part.

**Comment by roycewilliams** [comment]
Finally got some time to look at 0.5.0 alpha. Confirmed that emails are now sent with a solid HTML part and text part - and the "full name" in the From: and custom subject line are also working nicely now also - you guys rock!
