### ISSUE TITLE
feature: compress common substrings in device strings

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopussy#286]
Server version: 0.4.2

The GPUs/CPUs column on the Agents page could be more useful if some of the strings were compressed, as follows:

Advanced Micro Devices, Inc. [AMD/ATI] -> AMD
CPU @ -> [empty string]
Intel Corporation -> Intel
Intel(R) Core(TM) -> Core
Intel(R) Pentium(R) CPU -> Pentium
NVIDIA Corporation Device -> NVIDIA
NVIDIA GeForce -> NVIDIA

This would result in much more device-specific information visible in the column.

(In a few weeks I'm hoping to have some time to maybe work on some of these myself, so I'm documented things as I think of them, regardless of who gets to them first ;) )

**Comment by s3inlc** [comment]
I now applied this to the device strings on the agents overview page. For the start I just took your above proposals and included them. 
Feel free to contribute additional replacements / improvements in the corresponding file (`src/inc/defines/deviceCompress.php`)

**Comment by roycewilliams** [comment]
Most excellent - thanks!
