### ISSUE TITLE
unhandled exeption on windows when attaching windows client to linux hashcat server

### ISSUE THREAD

**Issue by ghost** [s3inlc/hashtopussy#287]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
Hashtopussy: 0.4.2

Current Client version
Client Version 0.45.8

Your current Hashcat version
3.6.0

The exact task command you are trying to run.

Debug output from the client by running "hashtopussy.exe debug"
C:\temp>hashtopussy.exe debug
Client Version 0.45.8
Checking for client updates
{"action":"update","type":"csharp","version":"0.45.8"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"S4FZ2ymqS8"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"S4FZ2ymqS8","force":1}
Downloading from https://hashcat.net/files/hashcat-3.6.0.7z
Downloading 100% @ 5,96 MB/s
C:\temp\7zr.exe x -y -o"C:\temp\hcClient" "C:\temp\hcClient.7z"
Extracting archive C:\temp\hcClient.7z...

Unbehandelte Ausnahme: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\temp\hcClient" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   bei hashtopussy.hashcatUpdateClass.updateHashcat()
   bei hashtopussy.Program.Main(String[] args)

Describe your problem in as much detail as possible " It's broke " is not a description.
i try to attach a client to hashtopussy server.
1) download client from http://10.14.11.101/agents.php?download=1
2) open command line and hashdopussy.exe
insert server http url : http://10.14.11.101/api/server.php
insert token
hashcat is downloaded, will be unpacked
exeption. 
tried to run command line as admin: same behavior

whenever i start hashtopussy client unhandled exeption comes up.

**Comment by DontFuckItUp** [comment]
another information, client operating system is windows 10 x64
firewall is turned off

**Comment by DontFuckItUp** [comment]
soo i testet the same setup within a ubuntu vm, same result:

-->
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Linux lab 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


Extracting  hashcat-3.6.0/rules/toggles3.rule
Extracting  hashcat-3.6.0/rules/toggles4.rule
Extracting  hashcat-3.6.0/rules/toggles5.rule
Extracting  hashcat-3.6.0/rules/unix-ninja-leetspeak.rule
Extracting  hashcat-3.6.0/hashcat32.bin
Extracting  hashcat-3.6.0/hashcat32.exe
Extracting  hashcat-3.6.0/hashcat64.bin
Extracting  hashcat-3.6.0/hashcat64.exe

Everything is Ok

Folders: 39
Files: 614
Size:       58005116
Compressed: 2605291

Unhandled Exception:
System.IO.DirectoryNotFoundException: Directory does not exist.
  at System.IO.Directory.Delete (System.String path) [0x0005d] in <77c9551943624fd18301ba6f78a841e5>:0
  at hashtopussy.hashcatUpdateClass.updateHashcat () [0x001d1] in <58c1b76d6bdb4ca3937046d822f9eae1>:0
  at hashtopussy.Program.Main (System.String[] args) [0x00181] in <58c1b76d6bdb4ca3937046d822f9eae1>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Directory does not exist.
  at System.IO.Directory.Delete (System.String path) [0x0005d] in <77c9551943624fd18301ba6f78a841e5>:0
  at hashtopussy.hashcatUpdateClass.updateHashcat () [0x001d1] in <58c1b76d6bdb4ca3937046d822f9eae1>:0
  at hashtopussy.Program.Main (System.String[] args) [0x00181] in <58c1b76d6bdb4ca3937046d822f9eae1>:0

what directory?

**Comment by s3inlc** [comment]
What is configured as root directory on this hashcat release on the server?

**Comment by DontFuckItUp** [comment]
i'm sorry i dont know what you exactly mean, can you please explain some more?
How can i find this information?

**Comment by DontFuckItUp** [comment]
Now the agent is running. Thank you. 


This issue is done. But another one comes up:
Getting task
{"action":"task","token":"Bd2rtwBVBv"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent

Log into server:
Files upload -files : text-file in following format
ggttt6577
(just the test password, nothing mor in it)

(It's the password from my test-wlan)

Then:
New Task: Inserting the HCCAPX Capture of my WLAN
Hashtype WPA/WPA2 (2500)

Nothing more.

Then:
Show agents
assign test machine

nothing. no work.

**Comment by s3inlc** [comment]
Ok that was what I suspected when it didn't found the directory after extracting.

Did you create a new task or just a new hashlist with the hccapx?

**Comment by DontFuckItUp** [comment]
i created both from scratch: first: new hashlist with the capture, then new task:
New Task looks like:
Name: 1234
Hashlist: Dropdown from the hashlist: name of the wlan-AP
Commandline changed to
-a0 #HL# wordlist_test.txt
chunk size untouched 600
status timer untouched 5
Benchmark-type runtime benchmark
color untouched
Task is cpu only untouched
task is small untouched
Skip given keyspace untouched

**Comment by s3inlc** [comment]
is the agent you try to run set as trusted or the hashlist and file set as not secret?

Because if the agent has not enough trusted status to access the hashlist and/or the file he doesn't get assigned to it.

Additionally check if your agents hardware was recognized correctly, so it shows the gpus.

**Comment by DontFuckItUp** [comment]
Hello, 
i can see the GPU/CPU
NVIDIA Quadro NVS...
Intel(R) Core(TM)...

okay. the linux client is working when i "trust" this client. 
the windows-client thow an exeption because of missing drivers, i will fix that first and come back then

**Comment by winxp5421** [comment]
We have not heard from you in a while. Please re-open if you still need help.
