### ISSUE TITLE
HTTP 500 error on install

### ISSUE THREAD

**Issue by rgw810** [s3inlc/hashtopussy#288]
I'm trying to install the newest Github version on Windows 10 Enterprise, I was having major issues with a negative length being reported and discovered XAMPP uses a 32-bit PHP. 

I set up Wampserver 3 using 64 bit PHP v5. When I select src for the install I'm greeted with a HTTP500 error. Looking at the PHP error log I see the following errors:

![capture](https://user-images.githubusercontent.com/11729295/30868538-f009adca-a2ac-11e7-8b9f-f4b882374ae4.PNG)

**Comment by winxp5421** [comment]
I believe this should fix your problem but, I should warn you I have no clue what I'm doing on your particular server config. Use caution. http://www.geeksengine.com/article/install-pear-on-windows.html

**Comment by rgw810** [comment]
Still got the same error, even tried this tutorial:
[http://www.tech-recipes.com/rx/29976/install-pear-on-windows-7-64x-using-wamp/](url)
