### ISSUE TITLE
Agent Does not Execute New Task

### ISSUE THREAD

**Issue by Ne0nd0g** [s3inlc/hashtopussy#289]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
`0.4.2`
Current Client version
`0.45.8`
Your current Hashcat version
`3.6.0`
The exact task command you are trying to run.

Debug output from the client by running "hashtopussy.exe debug"
```
Getting task
{"action":"task","token":"BcZfqjNDgW"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
```

Describe your problem in as much detail as possible " It's broke " is not a description.
When I assign an agent to a task, it automatically gets removed. I assigned the agent above to a task and then quickly checked the `Assignment` table and found that there was a new record. If you check back in about 10 seconds, the table is empty and the agent itself just keeps saying `No new task assigned to agent`.

```
mysql> select * from Assignment;
+--------------+--------+---------+-----------+
| assignmentId | taskId | agentId | benchmark |
+--------------+--------+---------+-----------+
|           74 |     52 |       2 | 0         |
+--------------+--------+---------+-----------+
```

```
mysql> select agentID, agentName, token, lastAct from Agent WHERE agentID = 2;
+---------+----------------+------------+---------+
| agentID | agentName      | token      | lastAct |
+---------+----------------+------------+---------+
|       2 | hashcracker001 | BcZfqjNDgW | task    |
+---------+----------------+------------+---------+
1 row in set (0.00 sec)
```

```
mysql> select taskID, taskName, attackCmd, priority from Task;
+--------+--------------------+---------------------------------------+----------+
| taskID | taskName           | attackCmd                             | priority |
+--------+--------------------+---------------------------------------+----------+
|     52 | HL44_20170928_1644 | #HL# 0-ABCD_Recovered_Sep-28-2017.txt |       10 |
+--------+--------------------+---------------------------------------+----------+
1 row in set (0.00 sec)
```

**Comment by s3inlc** [comment]
Is the agent set to be trusted?
In most cases this is the reason that an agent does not get assigned to a task, because either the required files or the hashlist is marked as secret.

**Comment by Ne0nd0g** [comment]
Yup, that did the trick. However, the Hashlist isn't marked as `Hashlist contains secret data`. Thanks for your help.
