### ISSUE TITLE
request for comment

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#290]
Hey dev, it's not a bug report, just need some clarification.

When I upload file to hashtopussy, its name and size is written in File table. My question is, what's the purpose of this 'size' column? I'm not asking about the obvious - it's of course size of uploaded file in bytes, but is it used anywhere else by hashtopussy?

**Comment by winxp5421** [comment]
No it is simply for user information.

On Oct 10, 2017, d2-d2 <notifications@github.com> wrote:

Hey dev, it's not a bug report, just need some clarification.

When I upload file to hashtopussy, its name and size is written in File table. My question is, what's the purpose of this 'size' column? I'm not asking about the obvious - it's of course size of uploaded file in bytes, but is it used anywhere else by hashtopussy?

**Comment by d2-d2** [comment]
thank you @winxp5421
