### ISSUE TITLE
[feature] script to generate basic cfg

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#291]
Hey Devs, this is not a bug report, just wanted to share a script with community + maybe 1 question.

So the script is written in Windows cmd. I figured that Linux ones are easy enough and everybody know how to do it, but Windows is sometimes tricky.

What's this all about. I needed a script that will generate initial configuration for hashtopussy based on my resources like rules and dictionaries. There is no point for me to upload them anywhere and then distribute to nodes when I can insert few things to DB and make a symbolic links to wl/rules that are shred by my rigs and also are used by standalone hashcat instances. Tanks to this I can faster modify and maintain such configuration.

So, here:
[script](https://pastebin.com/iEuUmc2e)
[example output](https://pastebin.com/DXmEL7JG)

Question:
- task.attackCmd column is varchar (512) - can it be extended freely? What would be the impact on hashtopussy.exe client? I know that hashcat can take very long command line parameters and it works, but since it is started by hashtopussy, are there any potential problems?

**Comment by s3inlc** [comment]
Thanks for sharing the scripts.

There should not be any problem with extending this varchar limit, there should not be any other limitation for the command line.

**Comment by d2-d2** [comment]
Thanks for the answer.
