### ISSUE TITLE
Incorrect speed displayed in Task Details

### ISSUE THREAD

**Issue by d2-d2** [s3inlc/hashtopussy#294]
Hello,

I am using v0.4.2 of hashtopussy. I've noticed that even though both agents are showing correct speeds (which are in GH/s), HP control panel is not:

https://prnt.sc/h3xs4j

Instead of MH/s it should be GH/s.

**Comment by s3inlc** [comment]
Did you switch the Hashcat version recently?

**Comment by d2-d2** [comment]
No, I'm still using v3.6.0.

**Comment by s3inlc** [comment]
When you start the clients, is there somewhere shown 'LEGACY'?

**Comment by s3inlc** [comment]
I suggest to upgrade to the newest client version (0.46.2), maybe your client is too old for the handling with both variants of Hashcat.

**Comment by d2-d2** [comment]
Yep, that helped. New version of hashtopussy.exe (0.46.2) fixed this problem. Thanks!
