### ISSUE TITLE
Incorrect keyspace calculation

### ISSUE THREAD

**Issue by Midniyht** [s3inlc/hashtopussy#295]
Current Server version: 0.4.3
Current Client version: 0.4.2
Your current Hashcat version: 4.0.0

WPA Attack: "-a3 #HL# -1 ABCDEFGHJKMNPQRTUVWXY346789 ?1?1?1?1?1?1?1?1"
Note: 8 chars required
Keyspace calculated at: 10460353203
This is the calculation for 7 chars. 

Debug output from the client by running "hashtopussy.exe debug"
Client Version 0.46.2
Connecting to server http://192.168.1.110/api/server.php
Checking for client updates
{"action":"update","type":"csharp","version":"0.46.2"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"LacIzbrq9d"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"LacIzbrq9d","force":0}
Hashcat version v4.0.0 found
Using new STATUS codes
Getting task
{"action":"task","token":"LacIzbrq9d"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent
Getting task
{"action":"task","token":"LacIzbrq9d"}
{"action":"task","response":"SUCCESS","task":"NONE"}

Mask is 8 chars but keyspace calculation is for 7 chars.

**Comment by winxp5421** [comment]
They keyspace value is pulled directly from hashcat's output. I'm 99% sure hashcat has these values correct.  Also your debug does not show anything with keyspace calculations so I do not have the needed information to double check anything.

**Comment by s3inlc** [comment]
These numbers are correct. There are two keyspace types which hashcat has. One is exactly the number of combinations which are tested (which is in the output PROGRESS in --machine-readable) and the second keyspace (which is given by --keyspace) is an internal number to measure the work for hashcat, but does not necessarily is the same like the number of combinations.

**Comment by Midniyht** [comment]
Ok, so you think I should just continue with the run. It just spooked me that I was after a keyspace of 27^8 and the value shown was for 27^7.

**Comment by s3inlc** [comment]
Yes, there should not be any problem with this task.
In case of bruteforce you can go down and try all lengths from 1-8 and you will see that it's always one less in the exponent for the keyspace.

**Comment by Midniyht** [comment]
Great, thanks for the quick response and sorry for wasting time.

**Comment by winxp5421** [comment]
You can verify the keyspace value manually. Run hashcat with the same command you supplied in hashtopussy and include option --keyspace the output from this should match the same value in hashtopussy. In short, you will be fine.
