### ISSUE TITLE
Unhandled exeption on windows client when start a TASK with RUNTIME BENCHMARK

### ISSUE THREAD

**Issue by fecosco** [s3inlc/hashtopussy#296]
Hashtopussy He issue comes when add a new TASK with RUNTIME BENCHMARK.

Server version 0.4.3
Current Client version0.46.2
Hashcat version 4.0.0
Windows 10 17.03 15063.674

-----------------------------------Debug information------------------------------------

C:\Hashtopussy>hashtopussy debug
Client Version 0.46.2
Connecting to server http://192.168.0.29/hash/api/server.php
Checking for client updates
{"action":"update","type":"csharp","version":"0.46.2"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"PU4OoYTfuV"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"PU4OoYTfuV","force":0}
Hashcat version v4.0.0 found
Using new STATUS codes
Getting task
{"action":"task","token":"PU4OoYTfuV"}
{"action":"task","response":"SUCCESS","task":79,"attackcmd":"-a 3 -w 4 #HL# ?l?l?l?l?l?l?l?l","cmdpars":" --hash-type=0","hashlist":19,"bench":30,"statustimer":15,"files":[],"benchType":"run","hashlistAlias":"#HL#"}
Server has assigned client with Task:79 and Hashlist:19
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"PU4OoYTfuV","hashlist":19}
{"action":"hashes","response":"SUCCESS","data":"SENQWAQAAAAAClZJUlRVQSAyNTQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAllwQJiAhG8bvKayr2S2CB5wVNJYoWdMve5torz7JDOwdYXObxgwEKo3aEq6Rixzy9fKvxOcyNBTSYhSzuUfrsOazZffgY3wBjG1XlSvrAJxagVC5uSHQhjQNCa6eQABAwB1AgEKAAAAAAAAAAAAAeUfrsOazZffgY3wBjG1XlSvrAJxagVC5uSHQhjQNCa6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYwFAEAAA+sAgEAAA+sBAEAAA+sAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}
Getting chunk...
{"action":"chunk","token":"PU4OoYTfuV","taskId":79}
{"action":"chunk","response":"SUCCESS","status":"benchmark"}
Using C:\Hashtopussy\files\ as working directory
C:\Hashtopussy\hashcat\hashcat64.exe  --hash-type=0 -a 3 -w 4 "C:\Hashtopussy\hashlists\19" ?l?l?l?l?l?l?l?l --runtime=30 --restore-disable --potfile-disable  --machine-readable --session=hashtopussy
Server requested the client benchmark this task for 30 seconds
nvmlDeviceGetFanSpeed(): Not Supported

No hashes loaded.

Unhandled exception: System.Collections.Generic.KeyNotFoundException: The provided key was not present in the dictionary.
   em System.ThrowHelper.ThrowKeyNotFoundException()
   em hashtopussy.taskClass.getChunk(Int32 inTask)
   em hashtopussy.taskClass.getTask()
   em hashtopussy.Program.Main(String[] args)

**Comment by s3inlc** [comment]
The hash data does not look like it is MD5, are you sure you set the hash type for the list correctly?

**Comment by fecosco** [comment]
Hash type is WPA2 and is set to 2500 - WPA2 on hashlist

**Comment by s3inlc** [comment]
ok, but on the issued task it says `--hash-type=0` aka MD5, for WPA2 it should be 2500, so the hashlist must be set wrong.

**Comment by fecosco** [comment]
I'll clear database and test again.

**Comment by fecosco** [comment]
Did you know wy #HL# can't get into CMD line? look this:

C:\Hashtopussy>hashtopussy debug
Client Version 0.46.2
Connecting to server http://192.168.0.29/hashtop/api/server.php
Checking for client updates
{"action":"update","type":"csharp","version":"0.46.2"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"g5RxlEmsYk"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"g5RxlEmsYk","force":0}
Hashcat version v4.0.0 found
Using new STATUS codes
Getting task
{"action":"task","token":"g5RxlEmsYk"}
{"action":"task","response":"SUCCESS","task":10,"attackcmd":"-a3 #HL#  ?l?l?l?l?l?l?l?l?l?l","cmdpars":" --hash-type=1000","hashlist":1,"bench":30,"statustimer":5,"files":[],"benchType":"speed","hashlistAlias":"#HL#"}
Server has assigned client with Task:10 and Hashlist:1
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"g5RxlEmsYk","hashlist":1}
Getting chunk...
{"action":"chunk","token":"g5RxlEmsYk","taskId":10}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client measure the keyspace for this task
Using C:\Hashtopussy\files\ as working directory
C:\Hashtopussy\hashcat\hashcat64.exe   --hash-type=1000 -a3   ?l?l?l?l?l?l?l?l?l?l --session=hashtopussy --keyspace --quiet
{"action":"keyspace","token":"g5RxlEmsYk","taskId":10,"keyspace":8031810176}
Getting chunk...
{"action":"chunk","token":"g5RxlEmsYk","taskId":10}
{"action":"chunk","response":"ERROR","message":"You are not assigned to this task!"}
ERROR
You are not assigned to this task!
Getting task
{"action":"task","token":"g5RxlEmsYk"}
{"action":"task","response":"SUCCESS","task":"NONE"}
No new task assigned to agent

**Comment by Ne0nd0g** [comment]
I was having a similar error. The new hashcat doesn't support the `-weak=0` flag and that causes it to break.

**Comment by blazer2x** [comment]
@Ne0nd0g the --weak flag was addressed last month see https://github.com/s3inlc/hashtopussy-agent/commit/6d87f2b65657e9ec129aa5b5e1b5f0aada9eeaeb

The agent should detect the correct version and if it's a non legacy version it will not apply the --weak check parameter.

**Comment by fecosco** [comment]
I fount the some reasons to strange behaviours:

A particular .hccapx file cause agents to exit whitought any troubleshoot information, try to use another .hccapx file;
If you use a mask that overflows the total Keyspace, application will exit with no errors.

Be sure that your file and mask culd run into hashcat, if it works great probably it will works great on Hashcatopussy. I try to use a 13 char mask and it cant run with especific sharsets, I need to change it to work.

If hashtopussy culd check masks or hash file integrity, it will make easy to comunity.

Nice job!

**Comment by winxp5421** [comment]
Doing some house cleaning. If you still need help or you think this was closed in error I'm sorry please re-open.
