### ISSUE TITLE
a help offer

### ISSUE THREAD

**Issue by curlyboi** [s3inlc/hashtopussy#309]
Hi guys, long time no see. I am very happy to see how big and good the project has grown. I have pretty much abandoned the original Hashtopus and recommended Hashtopussy right in the github readme. I don't have too much time but if there are any small mysterious bugs in the C# client (I got pretty good at that recently), let me know. Especially Windows stuff. Cheers :)

**Comment by winxp5421** [comment]
Awesome thanks! Without your original code none of this would be where it is today so thank you! There are some things floating around in the issues regarding the client you should check both the hashtopussy git and hashtopussy-agent git for anything that might interest you. Glad to have you aboard!

**Comment by winxp5421** [comment]
Doing some house cleaning and closing this. Feel free to contact us anytime!
