### ISSUE TITLE
WPA2 not working with 8-9 characters.

### ISSUE THREAD

**Issue by satcom886** [s3inlc/hashtopussy#313]
Hashtopussy server: 0.4.3
Hashtopussy client: 0.46.2
Hashcat version: 4.0.1

I'm having an issue with WPA2 cracking. When I run -a 3 #HL# ?l?l?l?l?l?l?l?l as the command for the task, assign an agent manually, the client is assigned, when I refresh the page, It is still showing as assigned. 
But when the agent that had the task assigned to it checks for tasks, It will be unassigned and the agent won't show any errors (I checked with hashtopussy.exe debug too).

I can provide any info you need...

**Comment by s3inlc** [comment]
Can you please provide the details information of the task and the agent (e.g. screenshots)?

Are there any other tasks which might have a higher priority than the wpa task?

**Comment by satcom886** [comment]
Of course!
![image](https://user-images.githubusercontent.com/28711937/35072150-b141ce84-fbe3-11e7-8f64-50f55fe5fb60.png)
![image](https://user-images.githubusercontent.com/28711937/35072183-d149526a-fbe3-11e7-8fa2-bd12c3b7ea25.png)

**Comment by satcom886** [comment]
There are no other tasks at all.

**Comment by s3inlc** [comment]
Thanks for providing the infos. 
Currently I don't see anything that could be the reason for this behavior.

So I did understand correctly. When you don't try to assign it manually, it will also never get assigned to the task?

**Comment by satcom886** [comment]
When the priority is set to the value that allows automatic assignments (not sure what the value is, that is why i have used 25), the agent will show as assigned. BUT the agent output will completely freeze until CTRL-C is pressed.

When assigning manually, the agent will just assign itself and the output would continue without errors.

**Comment by s3inlc** [comment]
Automatic assignment is done as soon as the priority is higher than 0.

At which point does the agent freeze in this case? What is the last output before this?

**Comment by satcom886** [comment]
That depends on whether the agent has tried to get the task info before or not. If not, there is just the usual hashtopussy checking updates, starting...

When the agent has already tried to contact the server about the task, it is stuck between getting task info and no new task assigned (I am actually not sure, that is the exact output. I am actually just writing this down from my head, so it would be maybe better to continue tomorrow, when I have access to the actual agent)

**Comment by s3inlc** [comment]
Ok, that sounds a bit strange, definitely should search if there is an issue.

Keep us up-to-date when you have some new infos. Everything more can help to find the issue.

**Comment by satcom886** [comment]
Thanks for your help so far, you have been doing great! I'l contact you when I have more info!

**Comment by winxp5421** [comment]
When you get access to the client again please post up some debug info by invoking the client with the debug flag 'hashtopussy.exe debug' this should give us a better idea what is happening.

**Comment by satcom886** [comment]
Ok, so I assigned a task, while the client was marked as "active", but hashtopussy was not running, after assigning I started the hashtopussy client.
![image](https://user-images.githubusercontent.com/28711937/35161280-fb587542-fd3f-11e7-86e3-6b619ade7a5c.png)

**Comment by satcom886** [comment]
It did not freeze this time, and the moment I started the agent, It just unassigned.

**Comment by s3inlc** [comment]
The only thing I currently see why this can happen, so just to be sure: The WPA in the hashlist isn't cracked yet, right?

**Comment by satcom886** [comment]
I have tested this on my own wifi, so I know the password, but the hashlist is not cracked.

**Comment by s3inlc** [comment]
Hmm ok, could you maybe also provide a screenshot of the hashlist detail page?

**Comment by winxp5421** [comment]
Is there any way we can get a sanitized version of your binary hashes SQL table?

**Comment by winxp5421** [comment]
If you create a brand new hashlist does the same behavior happen?

**Comment by satcom886** [comment]
Here we go!
![image](https://user-images.githubusercontent.com/28711937/35161739-640dfafc-fd41-11e7-8782-c60422721b45.png)
@winxp5421 I run the server on a Raspberry Pi 3, that could be the cause (but like when it works with 10+ characters, it should work with 8-9 as well...).
I have phpmyadmin installed, so if it could somehow download the database, then I would send it to ya.

**Comment by s3inlc** [comment]
You can export the full database with phpmyadmin. Just make sure to remove all personal details (password hash, email, ip, etc.)

**Comment by satcom886** [comment]
I am sending this in a spreadsheet, since I don't know how to edit an SQL DB.
[hashtopussy.xlsx](https://github.com/s3inlc/hashtopussy/files/1647357/hashtopussy.xlsx)
It should have all the details out, tho I have not found the hash...

**Comment by s3inlc** [comment]
An sql export is just a text-file with sql command where you can easily see the content and edit it with any text-editor. It's pretty difficult to read this spreadsheet.

**Comment by satcom886** [comment]
[hashtopussy.zip](https://github.com/s3inlc/hashtopussy/files/1647391/hashtopussy.zip)
I zipped it up, so I can upload it here...
And I have tried to create a new hashlist now (as @winxp5421 suggested) and got some bonus output!
![bez nazvu](https://user-images.githubusercontent.com/28711937/35163189-31515730-fd46-11e7-8886-48767b1a3712.png)

**Comment by s3inlc** [comment]
Oh I think I maybe have an idea what the problem is now. As you said you are running it on a raspberry pi, I assume you have only a 32bit OS there, correct?

In this case, the keyspace is just too large, as it's larger than the MAX_INT on a 32bit system and PHP cannot deal with this large number then.

**Comment by s3inlc** [comment]
As you can see on the task values, the keyspace produced an overflow, resulting in a negative keyspace number:

```
(62, '8chars', '-a 3 #HL# ?l?l?l?l?l?l?l?l', 3, 600, 5, -558124416, 0, 25, 'FFFFFF', 0, 0, 0, 0, 0)
```

**Comment by satcom886** [comment]
RPi has a 32 bit ARM CPU. This actually makes sense, but wouldn't using more characters cause an even bigger overflow?

**Comment by satcom886** [comment]
Oh wait! The CPU actually IS a 64 bit one! But I assume that the OS is not...

**Comment by winxp5421** [comment]
I think there is something else going on other than overflows personally but I could he wrong. Seems like odd behavior that " you are not assigned to this task " would happen

**Comment by winxp5421** [comment]
There has been reports of users running HtP on Rpi's without problems.

**Comment by s3inlc** [comment]
The "you are not assigned to this task" happens because the dispatched keyspace (0) is larger than the measured keyspace (which is negative) so the system thinks the task is completed and no work is needed.

I'm pretty sure that it's because the keyspace was too large for the system to handle. You need to check if the OS is also 64bit and then make sure that the php installation also is 64bits.

**Comment by winxp5421** [comment]
Nice yeah I did not think of that. @satcom886 please run the PHP checking script in the wiki and report back.

**Comment by satcom886** [comment]
Ok, I found the script on the wiki, but how do I run it? (sorry, I am a little bit of a noob when it comes to web stuff)

**Comment by s3inlc** [comment]
just put it into a file called test.php in the `src` folder and then call it with the browser.

**Comment by satcom886** [comment]
Ok, thanks!

**Comment by satcom886** [comment]
Exactly as you said! It is a 32-bit version!
I will try to get a 64-bit OS from somewhere and report back.
Thanks for your help guys!

**Comment by satcom886** [comment]
YES!!!! I have got it working with a 64-bit OS!!!
Great work guys, It is much appreciated!
The issue can now be closed.

**Comment by winxp5421** [comment]
Awesome glad everything has worked out.
