### ISSUE TITLE
"sticky" voucher

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopussy#314]
Allow a sticky client voucher.

Instead of only having one time vouchers allow a sticky option to make a specific voucher re-usable many times. This voucher should remain active until manually removed from the web UI.

**Comment by s3inlc** [comment]
I think I kinda already implemented this. In the Server Config you can set that vouchers won't get deleted after usage. So they remain active until they are delete manually.

**Comment by winxp5421** [comment]
Well then

**Comment by winxp5421** [comment]
bot test
