### ISSUE TITLE
error on upgrade 0.4.3 -> 0.5.0alpha

### ISSUE THREAD

**Issue by roycewilliams** [s3inlc/hashtopussy#317]
# php -f /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php
WARNING!!!!
This update contains some drastic changes and everything except users, agents, files, hashlists, pretasks and supertasks will be kept!
Backup the database before applying this update, in case something does not run as expected!
Do this upgrade ONLY if you really don't want to do a clean installation instead!
NOTE: If you have a lot of hashes imported, make sure that this process gets enough ram assigned!
Enter 'AGREE' to continue...
AGREE
Apply updates...
Disable checks... OK
Read Config table... OK
Read users... OK
Read agents... OK
Read files... OK
Read taskFile... OK
Read hashlists... OK
Read superhashlists... OK
Read hashes... OK
Read binary hashes... OK
Read tasks... OK
Read supertasks... OK
Read supertaskTasks... OK
Read hash types... OK
All data loaded! Removing old tables... OK
Importing new scheme... OK
Reload full include... PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php:24) in /var/www/hashtopussy/inc/load.php on line 8
PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php:24) in /var/www/hashtopussy/inc/load.php on line 8
OK
Starting with refilling data...
Create default access group... OK
Add Hashcat to CrackerBinaryType table... OK
Save hash types... OK
Save users... OK
Save agents... PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Notice:  Undefined index: devices in /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php on line 176
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'devices' cannot be null in /var/www/hashtopussy/dba/AbstractModelFactory.class.php:267
Stack trace:
#0 /var/www/hashtopussy/dba/AbstractModelFactory.class.php(267): PDOStatement->execute(Array)
#1 /var/www/hashtopussy/install/updates/update_v0.4.0_v0.5.0.php(180): DBA\AbstractModelFactory->massSave(Array)
#2 {main}
  thrown in /var/www/hashtopussy/dba/AbstractModelFactory.class.php on line 267

**Comment by s3inlc** [comment]
Thanks for the report. I pushed a fix for the error now. Can you please try again? (as you hopefully made a backup of the db before ;) )

Just as a note: The session_start warning is nothing to worry about, this happens because I include all the stuff later than normal, but this is required to be able to load from the old db.

**Comment by roycewilliams** [comment]
As a matter of fact, I didn't - didn't have much to lose. Apologies for that; if I had made a backup, I could re-test.
