### ISSUE TITLE
Rebrand project

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopussy#328]
Hey guys, I know hashtopus became hashtopussy but we are using this in corp style engagements so internally we refer to this as HTP, given the corporate climate would you consider a work safe flag that would use alternate branding, not hashtopussy but say HTP as some people (not me) find pussy offensive even though it could refer to a cat as in hashcat.

I work for a fairly conservative mega corp and questions are being asked.

**Comment by roycewilliams** [comment]
Considering the Hashtopus project (curlyboi) has effectively deferred to this one, the Hashtopus name could theoretically be adopted (with curlyboi's permission, of course)

**Comment by winxp5421** [comment]
We will certainly be discussing this in the coming days.

**Comment by exorcyst** [comment]
I second this.  I am a consultant and whenever I have to talk with clients (all the time) and talk about password cracking I have to talk around the name of this project.  I'd imagine a lot of other folks have to do this as well.

**Comment by winxp5421** [comment]
We are certainly open to suggestions.

**Comment by exorcyst** [comment]
hashkraken? i dunno, kinda works with the play on words and the squid reference or something, honestly I haven't given it too much thought...

**Comment by winxp5421** [comment]
S3, tycho and myself have been discussing this. maybe its not my place to say so as i feel this is S3's project Im just a influencer but, S3 as well as myself feel as though the userbase should have some say in the re-brand. After all this project is just as much for you as it its for us. 

I feel we should get as much input from the users as possible but, we are unsure exactly how to proceed with "opinion collection" as most people don't sit and read the github issues.  the current plan is to rebrand the new beta. This new beta brings forth expanded support for more cracking software in the future. Hashcat will probably always be our main focus but, we also feel that giving users tools and the freedom to use "Unofficially supported" software is a necessary thing. Hence why we feel it would be a good time to rebrand the project.

Anyway, first few ideas that came though our private discussions 

Hashtopolis
Octohash
Octocrack

**Comment by exorcyst** [comment]
It makes sense.  Just need to make sure that it is corp friendly and something that can be mentioned in briefings, etc...

Maybe an acronym to play off of something like cthulhu.  (Cracking The Hashes Using Lots of Users / CTHULU)

**Comment by s3inlc** [comment]
@exorcyst please email me on my hashes.org email or dm me on twitter.

**Comment by videoman** [comment]
Yeah- anytime I talk about what I'm using, I can in no uncertain terms mention the name of this project. It's pretty bad. Hashtopus was a play on Octopus, and worked. Hashtopussy doesn't work as pussy is slang, and not a word I could use in front of my own mother.

Please keep that in mind when renaming the project.

**Comment by winxp5421** [comment]
In an effort to make the hashtopussy project conform to a more politically neutral name we will be rebranding the project to "Hashtopolis". The repository and source will be renamed in the coming days.  The old URLs on the repo will still remain active.

Closing this issue now.

**Comment by marcus-brutus** [comment]
I know you guys already re-branded for RC1, but my vote would go HashKraken or just Kraken.  That way I could say I'm [releasing the Kraken.](http://i0.kym-cdn.com/photos/images/original/000/517/235/23e.jpg ) also am a fan of the Lovecraft references with Cthulhu.  Pretty much anything with monsters works for me.

**Comment by s3inlc** [comment]
The idea for the rebrand was also to have a name which is ideally unique or at least not very common so it's easy to find it with the name. There are many applications named kraken or contain kraken in their name.
