### ISSUE TITLE
simple Typing  error 

### ISSUE THREAD

**Issue by agentlimit** [s3inlc/hashtopussy#330]
#### Before you submit an issue please include the following information if you do not your issue will be closed.

Your current Server version located at the bottom of any hashtopussy webpage.
0.5.0 alpha

Current Client version
python client
Your current Hashcat version
4.0.1
The exact task command you are trying to run.
.
Debug output from the client by running "hashtopussy.exe debug"
.
Describe your problem in as much detail as possible " It's broke " is not a description.

I don't know If i should talk about it is simple. 
 
Missed Typing  in inc/handlers/AgentHandler.class.php   + 170 
         - the code " UI::printERror(....)   
         -  is it correct to  UI::printError(...)  
thanks.

**Comment by s3inlc** [comment]
Thanks for reporting
