### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by s3inlc** [s3inlc/hashtopussy#49]
There should be hooks which allow notifications on different channels like Mattermost, Email etc. on some actions.
It should be configurable for different kinds of events to have different notifications.

**Comment by s3inlc** [comment]
Add also the ability for getting notifications on specific log levels. So for example that you can configure to get an email when there is a log entry with level ERROR.

**Comment by s3inlc** [comment]
Notifications for following services are done:

* Notification logging to a file
* Email notifications
* Mattermost/Slack compatible notifications

**Comment by jasongraf** [comment]
@s3inlc , I have setup a web hook for Slack and for Teams, but the notifications are not being sent. I was able to craft a curl command manually from my Hashtopolis server, and those commands worked properly to post a message in both Slack and Teams. Can you recommend a good place to look for possible a log of those notification events and what is happening?
